In [1]:
import os
print(os.getcwd())
print(os.listdir())
print(list(os.listdir()))

e:\Admin\Desktop\Python\Python Anand Notes
['.git', '.vscode', 'abc.ipynb', 'abc.py', 'Aggregation.ipynb', 'Control Flow.ipynb', 'Control_Flow_Practice.ipynb', 'Data', 'Data Cleaning 1.ipynb', 'Data Cleaning 2.ipynb', 'Datasets', 'DataStructures_Session.ipynb', 'Dictionaries.ipynb', 'Error handling.ipynb', 'f string formatting.ipynb', 'File handling.ipynb', 'Hospital_Practice_Lists.ipynb', 'Hospital_Practice_Sets_Dicts_Nested.ipynb', 'Hospital_Strings_Practice.ipynb', 'Lists & Tuples.ipynb', 'Logic Basics.ipynb', 'Loops & Iteration 1.ipynb', 'Loops & Iteration 2.ipynb', 'Loops_Iteration_1_Practice.ipynb', 'Modular Code 1.ipynb', 'Modular Code 2.ipynb', 'new_orders.txt', 'Numpy Core.ipynb', 'Orders.txt', 'Pandas Ingestion.ipynb', 'Pandas Selection.ipynb', 'prod', 'Products.txt', 'Python Quiz.ipynb', 'Python_Mixed_Practice_10Q.ipynb', 'PYT_05.ipynb', 'Sets.ipynb', 'Strings.ipynb', 'Theory_Revision_Reference.md', 'Transformation.ipynb']
['.git', '.vscode', 'abc.ipynb', 'abc.py', 'Aggregation.ipynb', 'Control Flow.ipynb', 'Control_Flow_Practice.ipynb', 'Data', 'Data Cleaning 1.ipynb', 'Data Cleaning 2.ipynb', 'Datasets', 'DataStructures_Session.ipynb', 'Dictionaries.ipynb', 'Error handling.ipynb', 'f string formatting.ipynb', 'File handling.ipynb', 'Hospital_Practice_Lists.ipynb', 'Hospital_Practice_Sets_Dicts_Nested.ipynb', 'Hospital_Strings_Practice.ipynb', 'Lists & Tuples.ipynb', 'Logic Basics.ipynb', 'Loops & Iteration 1.ipynb', 'Loops & Iteration 2.ipynb', 'Loops_Iteration_1_Practice.ipynb', 'Modular Code 1.ipynb', 'Modular Code 2.ipynb', 'new_orders.txt', 'Numpy Core.ipynb', 'Orders.txt', 'Pandas Ingestion.ipynb', 'Pandas Selection.ipynb', 'prod', 'Products.txt', 'Python Quiz.ipynb', 'Python_Mixed_Practice_10Q.ipynb', 'PYT_05.ipynb', 'Sets.ipynb', 'Strings.ipynb', 'Theory_Revision_Reference.md', 'Transformation.ipynb']

In [2]:
import pandas as pd
df=pd.read_csv("Datasets/all_athlete_games.csv")

C:\Users\anand\AppData\Local\Temp\ipykernel_9752\2370261064.py:2: DtypeWarning: Columns (0: Sport Disciplines, 1: Event List) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("Datasets/all_athlete_games.csv")

In [3]:
#GroupBy - "The split, apply, combine idea"

#groupby does three steps in one linr - split, apply, and combine.
#For example if you have a dataset that you want to sort per country, then you split it first then you do some aggregation with it, count rows in it or averaging --> This is the apply part
#At the end you take all those results and stack them back into one final table --> This is the combine part.

#simple group by
df.groupby('Sport').size()

#split rows into piles by sport then count the number of rows in each pile including any missing values in other columns

Sport
3x3 Basketball      64
Aeronautics          1
Alpine Skiing     8829
Alpinism            25
Archery           2592
                  ...
Tug-Of-War         170
Volleyball        3692
Water Polo        4132
Weightlifting     4134
Wrestling         7443
Length: 84, dtype: int64

In [4]:
#Grouping them picking a column and applying an aggregation function to it
#df.groupby('Sport')['Age'].mean() --> result in series
df.groupby('Sport')[['Age']].mean() #dataframe

                      Age
Sport
3x3 Basketball  28.437500
Aeronautics     26.000000
Alpine Skiing   23.205462
Alpinism        38.812500
Archery         27.789411
...                   ...
Tug-Of-War      29.309524
Volleyball      25.403747
Water Polo      25.763225
Weightlifting   25.533859
Wrestling       25.851554

[84 rows x 1 columns]

In [5]:
#groupby multiple columns 
result=df.groupby(['Sport','Season'])['Age'].mean()
result.index
df.groupby(['Sport','Season'])['Age'].mean()
#Now each pile is defined by a combination of 2 columns (sport and season) and then aggregated
            
#This is a multi-indexed result set

Sport           Season
3x3 Basketball  Summer    28.437500
Aeronautics     Summer    26.000000
Alpine Skiing   Winter    23.205462
Alpinism        Summer    35.250000
                Winter    40.000000
                            ...
Tug-Of-War      Summer    29.309524
Volleyball      Summer    25.403747
Water Polo      Summer    25.763225
Weightlifting   Summer    25.533859
Wrestling       Summer    25.851554
Name: Age, Length: 87, dtype: float64

In [6]:
#Coverting this into a normal table (flattening multi column group by back into a table)
df.groupby(['Sport','Season'])['Age'].mean().reset_index()

#reset index turns the multi-index grouping labels back into regular columns, giving you an ordinary flat table
#easier to read, filter or plot afterwards.

             Sport  Season        Age
0   3x3 Basketball  Summer  28.437500
1      Aeronautics  Summer  26.000000
2    Alpine Skiing  Winter  23.205462
3         Alpinism  Summer  35.250000
4         Alpinism  Winter  40.000000
..             ...     ...        ...
82      Tug-Of-War  Summer  29.309524
83      Volleyball  Summer  25.403747
84      Water Polo  Summer  25.763225
85   Weightlifting  Summer  25.533859
86       Wrestling  Summer  25.851554

[87 rows x 3 columns]

In [7]:
#medal count by country

df.groupby(['NOC','Season'])['Medal'].count()

#Count gives you the count of rows excluding missing values
#Size gives you the count of rows including missing values

NOC  Season
AFG  Summer      2
AHO  Summer      1
     Winter      0
AIN  Summer      0
     Winter      0
              ...
YUG  Summer    383
     Winter      7
ZAM  Summer      2
ZIM  Summer     22
     Winter      0
Name: Medal, Length: 366, dtype: int64

In [8]:
#Aggregation --> .agg()

#We usualyy do sum,mean,count which gives us one calculation per group by.
#.agg is used when you need several calculations at once
#example --> average age and total meadl count and number of athletes, all per country in one table

#Multiple aggregation on the same column
df.groupby('NOC')['Age'].agg(['mean','min','max','count'])

          mean   min   max  count
NOC
AFG  23.696629  17.0  35.0     89
AHO  26.589744  15.0  55.0     78
AIN  24.750000  16.0  38.0     32
ALB  26.477273  16.0  55.0     88
ALG  24.729560  14.0  39.0    636
..         ...   ...   ...    ...
YEM  21.904762  15.0  38.0     42
YMD  23.600000  17.0  33.0      5
YUG  24.745721  13.0  54.0   2454
ZAM  23.462963  15.0  38.0    216
ZIM  25.239875  13.0  54.0    321

[234 rows x 4 columns]

## Numeric aggregations

| Aggregation | Meaning |
|---|---|
| `'sum'` | total of all values |
| `'mean'` | average |
| `'median'` | middle value |
| `'min'` | smallest value |
| `'max'` | largest value |
| `'std'` | standard deviation (spread around the mean) |
| `'var'` | variance |

## Counting aggregations (numeric or text)

| Aggregation | Meaning |
|---|---|
| `'count'` | number of non-missing values |
| `'size'` | number of rows total (includes missing values) |
| `'nunique'` | number of distinct (unique) values |

In [9]:
#different aggregation for different columns
df.groupby('NOC').agg({'Age':'mean','Medal':'count','Name':'nunique'})

           Age  Medal  Name
NOC
AFG  23.696629      2   114
AHO  26.589744      1    55
AIN  24.750000      0    52
ALB  26.477273      0    66
ALG  24.729560     17   460
..         ...    ...   ...
YEM  21.904762      0    37
YMD  23.600000      0     5
YUG  24.745721    390  1269
ZAM  23.462963      2   206
ZIM  25.239875     22   208

[234 rows x 3 columns]

In [10]:
#multiple Aggregations for multiple columns
df.groupby('NOC').agg({'Age':['mean','std'],'Medal':'count'})

           Age           Medal
          mean       std count
NOC
AFG  23.696629  4.289004     2
AHO  26.589744  8.153457     1
AIN  24.750000  5.117963     0
ALB  26.477273  8.668847     0
ALG  24.729560  4.184991    17
..         ...       ...   ...
YEM  21.904762  5.230350     0
YMD  23.600000  6.655825     0
YUG  24.745721  4.668782   390
ZAM  23.462963  4.159441     2
ZIM  25.239875  6.757526    22

[234 rows x 3 columns]

In [11]:
#naming your own aggregation columns
df.groupby('NOC').agg(avg_age=('Age','mean'),total_medals=('Medal','count'),num_athletes=('Name','nunique'))

       avg_age  total_medals  num_athletes
NOC
AFG  23.696629             2           114
AHO  26.589744             1            55
AIN  24.750000             0            52
ALB  26.477273             0            66
ALG  24.729560            17           460
..         ...           ...           ...
YEM  21.904762             0            37
YMD  23.600000             0             5
YUG  24.745721           390          1269
ZAM  23.462963             2           206
ZIM  25.239875            22           208

[234 rows x 3 columns]

In [12]:
#Positional Aggregation

df.groupby('NOC')['Name'].first()
#This is just going to give us the first row entry

df.groupby('NOC')['Name'].last()
#This is just going to give us the last row entry

NOC
AFG      Mohammad Samim FAIZAD
AHO    Churandy Thomas Martina
AIN               ZUEVA Marina
ALB                XHEPA Denni
ALG            Nihed BENCHADLI
                ...
YEM            Samer AL-YAFAEE
YMD      Mohamed Mahfood Sayed
YUG        Borislav Vujadinovi
ZAM              Sitali KAKENE
ZIM         Denilson CYPRIANOS
Name: Name, Length: 234, dtype: str

In [13]:
df.sort_values('Year').groupby('Name')['Sport'].last()

#Sort the whole dataframe by year then group by athlete and last gets the Athleet's most recent sport

Name
  Gabrielle Marie "Gabby" Adcock (White-)        Badminton
 Eleonora Margarida Josephina Scmitt              Swimming
 Jean Hauptmanns                                 Wrestling
 Luis ngel Fernando de los Santos Grossi           Cycling
 Th Anh                                            Fencing
                                                 ...
zge Krdar emberci                               Volleyball
zlem Kaya                                        Athletics
zman Graud                                        Shooting
zzet Safer                                       Athletics
zzet nce                                     Weightlifting
Name: Sport, Length: 159942, dtype: str

In [14]:
#Custom functions inside aggregation
df.groupby('NOC')['Age'].agg(lambda x:x.max()-x.min())

#age range per country

NOC
AFG    18.0
AHO    40.0
AIN    22.0
ALB    39.0
ALG    25.0
       ...
YEM    23.0
YMD    16.0
YUG    41.0
ZAM    23.0
ZIM    41.0
Name: Age, Length: 234, dtype: float64

In [15]:
#count how many people are having age> per country
df.groupby('NOC')['Age'].agg(lambda x:(x>50).sum())

NOC
AFG    0
AHO    2
AIN    0
ALB    2
ALG    0
      ..
YEM    0
YMD    0
YUG    1
ZAM    0
ZIM    3
Name: Age, Length: 234, dtype: int64

In [16]:
#named reusable custom funtion

def age_range(ages):
    return ages.max()-ages.min()

df.groupby('NOC')['Age'].agg(age_range)

NOC
AFG    18.0
AHO    40.0
AIN    22.0
ALB    39.0
ALG    25.0
       ...
YEM    23.0
YMD    16.0
YUG    41.0
ZAM    23.0
ZIM    41.0
Name: Age, Length: 234, dtype: float64

In [17]:
#Combining custom function with built-in function

df.groupby('NOC')['Age'].agg(['mean','std',age_range])

          mean       std  age_range
NOC
AFG  23.696629  4.289004       18.0
AHO  26.589744  8.153457       40.0
AIN  24.750000  5.117963       22.0
ALB  26.477273  8.668847       39.0
ALG  24.729560  4.184991       25.0
..         ...       ...        ...
YEM  21.904762  5.230350       23.0
YMD  23.600000  6.655825       16.0
YUG  24.745721  4.668782       41.0
ZAM  23.462963  4.159441       23.0
ZIM  25.239875  6.757526       41.0

[234 rows x 3 columns]

In [18]:
#Pivoting -pivot_table, crosstab

#Both reshape our data into a grid --? rows and columns as two categories.

#Pivot_table() --> fills cells with an aggregated value you specify(mean,sum,count). More flexible

#crosstab() --> fills cells with frequency counts by default (how many rows fall into each row/column combination) 
# Simpler purpose - built for counting

df.pivot_table(index='Season',columns='Gender',values='Age',aggfunc='mean')

Gender     Female       Male
Season
Summer  24.116298  26.500560
Winter  24.014398  25.504261

In [19]:
df.pivot_table(index='Season',columns='Gender',values='Age',aggfunc='count')

Gender  Female    Male
Season
Summer   71747  167850
Winter   15072   33207

In [20]:
df.pivot_table(index='Season',columns='Gender',values='Age',aggfunc=['mean','count'])

             mean             count
Gender     Female       Male Female    Male
Season
Summer  24.116298  26.500560  71747  167850
Winter  24.014398  25.504261  15072   33207

In [21]:
#Filling in missing combinations
df.pivot_table(index='NOC',columns='Season',values='Medal',aggfunc='count',fill_value=0)

Season  Summer  Winter
NOC
AFG          2       0
AHO          1       0
AIN          0       0
ALB          0       0
ALG         17       0
..         ...     ...
YEM          0       0
YMD          0       0
YUG        383       7
ZAM          2       0
ZIM         22       0

[234 rows x 2 columns]

In [22]:
#Crosstab

pd.crosstab(df['Season'],df['Gender'])

Gender  Female    Male
Season
Summer   72164  176622
Winter   16442   35038

In [23]:
#normalize converts raw counts into proportions of the whole table(adding up to 1.0 overall)
#here we are normalizing across the whole table
pd.crosstab(df['Season'],df['Gender'],normalize=True)

Gender    Female      Male
Season
Summer  0.240334  0.588218
Winter  0.054758  0.116690

In [28]:
# normalize =index normalizes within each row,so each season's row 
# shows what fraction was male vs female adding up to 1.0 per row
pd.crosstab(df['Season'],df['Gender'],normalize='index')

Gender    Female      Male
Season
Summer  0.290065  0.709935
Winter  0.319386  0.680614

In [25]:
#For each country how many distinct athletes complted
df.groupby('NOC')[['Name']].agg('nunique')

#Whats the average age shown as a table with season across the rows and gender across the columns
df.pivot_table(index='Season',columns='Gender',values='Age',aggfunc='mean')

#How many entries are there for season and gender combination
df.groupby(['Season','Gender']).size() #and using crosstab we can write like this
pd.crosstab(df['Season'],df['Gender'])

Gender  Female    Male
Season
Summer   72164  176622
Winter   16442   35038