In [75]:
#Duplicates 

#check for entire row duplicates

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("./datasets/all_athlete_games.csv")
regions=pd.read_csv("./datasets/all_regions.csv")
df.shape

print("Full row duplicates",df.duplicated().sum())

C:\Users\anand\AppData\Local\Temp\ipykernel_14584\3651872876.py:10: DtypeWarning: Columns (0: Sport Disciplines, 1: Event List) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("./datasets/all_athlete_games.csv")

Full row duplicates 0

In [76]:
#exclude Entry ID -the one column auto generated that always differs

cols=[c for c in df.columns if c!='Entry ID']
print("Duplicates excluding entry ID:",df.duplicated(subset=cols).sum())

Duplicates excluding entry ID: 1386

In [77]:
#df.drop_duplicates()

#syntax- 
#df.drop_duplicates(subset,keep,inplace)

print("Before:",df.shape)

df_clean=df.drop_duplicates(subset=cols,keep='first')
print('After keep=first',df_clean.shape)

df_clean=df.drop_duplicates(subset=cols,keep=False)
print('After keep=False',df_clean.shape)

Before: (300266, 14)
After keep=first (298880, 14)
After keep=False (298267, 14)

| Argument | Description | Default |
|---|---|---|
| subset | Which columns to check for duplication | None — all columns |
| keep | Which copy to keep: "first", "last", or False (drop all copies) | "first" |
| inplace | Modify original DataFrame | False |

In [78]:
#String operations

#.str accessor
print(df['Sport'].head(3))
print(df['Sport'].str.lower().head(3))

df['Sport']=df['Sport'].str.lower() #if u want to keep the change
print(df['Sport'].head(3))

0    Tennis
1    Tennis
2    Tennis
Name: Sport, dtype: str
0    tennis
1    tennis
2    tennis
Name: Sport, dtype: str
0    tennis
1    tennis
2    tennis
Name: Sport, dtype: str

In [79]:
#.str.contains() - search inside text - case-sensitive

athletics_count=df['Sport'].str.contains('athletics',case=False,na=False).sum()
print("Rows containing 'Athletics':",athletics_count)

Rows containing 'Athletics': 40942

| Method | What It Does | Example |
|---|---|---|
| .str.lower() | Converts text to lowercase | "Python" → "python" |
| .str.upper() | Converts text to uppercase | "Python" → "PYTHON" |
| .str.title() | Capitalizes the first letter of each word | "data analyst" → "Data Analyst" |
| .str.capitalize() | Capitalizes only the first letter of the string | "python" → "Python" |
| .str.strip() | Removes leading and trailing whitespace | " Python " → "Python" |
| .str.lstrip() | Removes whitespace from the left | " Python" → "Python" |
| .str.rstrip() | Removes whitespace from the right | "Python " → "Python" |
| .str.contains("text") | Returns True/False if the text appears anywhere | "Power BI" contains "BI" → True |
| .str.startswith("text") | Checks if the string starts with the given text | "Python" starts with "Py" → True |
| .str.endswith("text") | Checks if the string ends with the given text | "report.csv" ends with ".csv" → True |
| .str.replace("old", "new") | Replaces matching text | "Power BI" → "Power Query" |
| .str.split(",") | Splits a string into a list | "A,B,C" → ["A", "B", "C"] |
| .str.len() | Returns the length of each string | "Python" → 6 |
| .str.count("text") | Counts occurrences of a substring | "banana" count "a" → 3 |
| .str.find("text") | Returns the index of the first occurrence (-1 if not found) | "Python" find "th" → 2 |
| .str.slice(0, 3) | Extracts characters by position | "Python" → "Pyt" |
| .str.isalpha() | Checks if all characters are letters | "Python" → True |
| .str.isnumeric() | Checks if all characters are digits | "12345" → True |
| .str.isalnum() | Checks if all characters are letters or digits |

In [80]:
#General Pandas series methods-
print("Output 1",df['Team'].unique()) #unique/distinct values
print()
print("Output 2",df['Team'].nunique()) #count of distinct values
print()
print("Output 3",df['Medal'].value_counts()) #count of each value appearing
print()
print("Output 4",df['Age'].isna()) #True/False is this value missing
print()
print("Output 5",df['Age'].notna()) #opposite of isna()
print()
print("Output 6",df['Age'].fillna(0)) #filling the missing values
print()
print("Output 7",df['Year'].sort_values()) #sort the values
print()
print("Output 8",df['Team'].isin(['Greece','France'])) #true/false membership test
print()
print("Output 9",df['Team'].replace('Greece','Hellas')) #replace exact values 
#no .str needed for exact value match

Output 1 <StringArray>
[               'Greece',              'Greece-3',         'Great Britain',
           'Switzerland',         'United States',               'Germany',
 'Great Britain/Germany',                'France',              'Greece-1',
               'Hungary',
 ...
     'Virgin Islands, B',                 'Korea',                   'EOR',
     'Brunei Darussalam',        'Centr Afric Re',  'Bosnia & Herzegovina',
               'Lao PDR',              'DR Congo',             'DPR Korea',
                     nan]
Length: 1221, dtype: str

Output 2 1220

Output 3 Medal
Gold      14172
Bronze    14162
Silver    13898
Name: count, dtype: int64

Output 4 0         True
1         True
2         True
3         True
4         True
          ...
300261    True
300262    True
300263    True
300264    True
300265    True
Name: Age, Length: 300266, dtype: bool

Output 5 0         False
1         False
2         False
3         False
4         False
          ...
300261    False
300262    False
300263    False
300264    False
300265    False
Name: Age, Length: 300266, dtype: bool

Output 6 0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
300261    0.0
300262    0.0
300263    0.0
300264    0.0
300265    0.0
Name: Age, Length: 300266, dtype: float64

Output 7 0         1896
1         1896
2         1896
3         1896
4         1896
          ...
300261    2026
300262    2026
300263    2026
300264    2026
300265    2026
Name: Year, Length: 300266, dtype: int64

Output 8 0          True
1         False
2          True
3         False
4          True
          ...
300261    False
300262    False
300263    False
300264    False
300265    False
Name: Team, Length: 300266, dtype: bool

Output 9 0           Hellas
1         Greece-3
2           Hellas
3         Greece-3
4           Hellas
            ...
300261         NaN
300262         NaN
300263         NaN
300264         NaN
300265         NaN
Name: Team, Length: 300266, dtype: str

In [81]:
#Regex -basic patterns

# Regex (regular expressions) is a mini pattern-matching language for text — 
# instead of searching for an exact word,
# you describe a shape of text you're looking for.

| Symbol | Meaning | Example |
|---|---|---|
| \D | Any non-digit character | letter, other characters |
| \d | Any single digit (0–9) | \d\d\d\d matches a 4-digit year |
| \w | Any letter, digit, or underscore | \w+ matches a whole word |
| ^ | Start of the text | ^A matches text that begins with A |
| $ | End of the text | son$ matches text that ends with "son" |
| + | One or more thing before it | \d+ matches 5,42,1500- any run of digits |
|(...)| a "Capture group"- marks the part you actually wanted to extract | -(\d)$ matches the whole -3 but only captures the 3 |

In [82]:
#Match exactly a single digit
print(df['Team'].isna().sum())

print(df[df['Team'].str.contains(r'-\d$',na=False)]['Team'].unique()) #r is for raw string
print(df['Team'].str.extract(r'-(\d)$')) #r is for raw string

2916
<StringArray>
[                 'Greece-3',                  'Greece-1',
                  'Greece-2',                  'Martha-1',
       'Favorite Hammonia-3', 'Club Nautique de Dieppe-5',
              'Carabinier-5',           'Pettit-Poucet-6',
                'Crabe II-1',                'Crabe II-4',
 ...
               'Singapore-2',                'Slovenia-1',
                'Slovenia-2',               'Singapore-1',
                 'Belarus-1',                    'Cuba-1',
                    'Cuba-2',                 'Belarus-2',
                  'Serbia-2',                  'Serbia-1']
Length: 333, dtype: str
          0
0       NaN
1         3
2       NaN
3         3
4       NaN
...     ...
300261  NaN
300262  NaN
300263  NaN
300264  NaN
300265  NaN

[300266 rows x 1 columns]

In [83]:
#Starts with a digit
df[df['Team'].str.contains(r'^\d',na=False)]

,Entry ID,Name,Gender,Age,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List
48309,48310,Harald Fereberger,Male,23.0,30. Februar,AUT,1952,Summer,Helsinki,sailing,Sailing Mixed Two Person Keelboat,NaN,NaN,NaN
54043,54044,Harald von Musil,Male,44.0,30. Februar,AUT,1952,Summer,Helsinki,sailing,Sailing Mixed Two Person Keelboat,NaN,NaN,NaN

In [84]:
#Example 1: Splitting the team suffix
df['team_variant']=df['Team'].str.extract(r'-(\d)$')

print(df['Team'].head())
print(df['team_variant'].head())

0      Greece
1    Greece-3
2      Greece
3    Greece-3
4      Greece
Name: Team, dtype: str
0    NaN
1      3
2    NaN
3      3
4    NaN
Name: team_variant, dtype: str

In [85]:
print(df['Team'].str.extract(r'-(\d)$'))

          0
0       NaN
1         3
2       NaN
3         3
4       NaN
...     ...
300261  NaN
300262  NaN
300263  NaN
300264  NaN
300265  NaN

[300266 rows x 1 columns]

In [86]:
df['team_variant']=df['Team'].str.extract(r'-(\d)$')
print(df['team_variant'])

0         NaN
1           3
2         NaN
3           3
4         NaN
         ...
300261    NaN
300262    NaN
300263    NaN
300264    NaN
300265    NaN
Name: team_variant, Length: 300266, dtype: str

In [87]:
import pandas as pd
import numpy as np

df=pd.read_csv("Datasets/all_athlete_games.csv",low_memory=False)

#low memory=Flase tells pandas to not read in chunks but the whole file at once, then figure out each column's type from the complete picture, at the cost of using more memory.

In [88]:
# DataFrame vs Series 

# df stands for dataframe -  2D (Whole table)
# series - 1D (single column)

print(df['Team']) # series 
print(type(df['Team']))

0           Greece
1         Greece-3
2           Greece
3         Greece-3
4           Greece
            ...
300261         NaN
300262         NaN
300263         NaN
300264         NaN
300265         NaN
Name: Team, Length: 300266, dtype: str
<class 'pandas.Series'>

In [89]:
print(df[['Team']]) # DataFrame 
print(type(df[['Team']]))

            Team
0         Greece
1       Greece-3
2         Greece
3       Greece-3
4         Greece
...          ...
300261       NaN
300262       NaN
300263       NaN
300264       NaN
300265       NaN

[300266 rows x 1 columns]
<class 'pandas.DataFrame'>

In [90]:
print(df['Age']) #Series
print(df[['Age']]) #Dataframe
print(df[['Age','Team']]) #Dataframe
print(df.iloc[0]) #Series

#Boolean mask
mask=df['Age']>25 #A series of True/False values for each row in the dataframe
df[mask] #filters rows using the boolean mask, still a dataframe, not a series
df[mask]['Team'] #filters rows, then one column using the boolean mask-->series not a dataframe.
df[mask][['Team']] #filters rows, then kept column in brackets using the boolean mask-->dataframe, not a series

#Important: row filtering never collapses a DataFrame into a Series by itself no matter how few rows match.
# It's only when you also pick a single column afterward (['Team'] with single brackets) that it becomes a Series.

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
300261   NaN
300262   NaN
300263   NaN
300264   NaN
300265   NaN
Name: Age, Length: 300266, dtype: float64
        Age
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
300261  NaN
300262  NaN
300263  NaN
300264  NaN
300265  NaN

[300266 rows x 1 columns]
        Age      Team
0       NaN    Greece
1       NaN  Greece-3
2       NaN    Greece
3       NaN  Greece-3
4       NaN    Greece
...     ...       ...
300261  NaN       NaN
300262  NaN       NaN
300263  NaN       NaN
300264  NaN       NaN
300265  NaN       NaN

[300266 rows x 2 columns]
Entry ID                                  1
Name                 Aristidis Akratopoulos
Gender                                 Male
Age                                     NaN
Team                                 Greece
NOC                                     GRE
Year                                   1896
Season                               Summer
City                                 Athina
Sport                                Tennis
Event                  Tennis Men's Singles
Medal                                   NaN
Sport Disciplines                       NaN
Event List                              NaN
Name: 0, dtype: object

                 Team
37      United States
38      United States
39      United States
74            Germany
75            Germany
...               ...
297327          Japan
297339         Greece
297341    Netherlands
297344         Uganda
297348         France

[125071 rows x 1 columns]

In [91]:
mask=df['Age']>25
print(mask)

0         False
1         False
2         False
3         False
4         False
          ...
300261    False
300262    False
300263    False
300264    False
300265    False
Name: Age, Length: 300266, dtype: bool

In [92]:
df[mask]

,Entry ID,Name,Gender,Age,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List
37,38,James Brendan Bennet Connolly,Male,27.0,United States,USA,1896,Summer,Athina,Athletics,Athletics Men's High Jump,Silver,NaN,NaN
38,39,James Brendan Bennet Connolly,Male,27.0,United States,USA,1896,Summer,Athina,Athletics,Athletics Men's Long Jump,Bronze,NaN,NaN
39,40,James Brendan Bennet Connolly,Male,27.0,United States,USA,1896,Summer,Athina,Athletics,Athletics Men's Triple Jump,Gold,NaN,NaN
74,75,Alfred Flatow,Male,26.0,Germany,GER,1896,Summer,Athina,Gymnastics,Gymnastics Men's Horse Vault,NaN,NaN,NaN
75,76,Alfred Flatow,Male,26.0,Germany,GER,1896,Summer,Athina,Gymnastics,Gymnastics Men's Parallel Bars,Gold,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297327,297328,TSUTSUE Kaito,Male,26.0,Japan,JPN,2024,Summer,Paris,NaN,NaN,NaN,['Athletics'],"[""Men's 400m Hurdles""]"
297339,297340,Despoina PAPAMICHAIL,Female,31.0,Greece,GRE,2024,Summer,Paris,NaN,NaN,NaN,['Tennis'],"[""Women's Doubles""]"
297341,297342,Anne van de WIEL,Female,27.0,Netherlands,NED,2024,Summer,Paris,NaN,NaN,NaN,['Athletics'],"[""Women's 4 x 400m Relay""]"
297344,297345,Annet Chemengich CHELANGAT,Female,31.0,Uganda,UGA,2024,Summer,Paris,NaN,NaN,NaN,['Athletics'],"[""Women's 10,000m""]"
297348,297349,Kevin STAUT,Male,43.0,France,FRA,2024,Summer,Paris,NaN,NaN,NaN,['Equestrian'],[Jumping Team]

In [93]:
df[mask]['Team']

37        United States
38        United States
39        United States
74              Germany
75              Germany
              ...
297327            Japan
297339           Greece
297341      Netherlands
297344           Uganda
297348           France
Name: Team, Length: 125071, dtype: str

In [94]:
df[mask][['Team']]

                 Team
37      United States
38      United States
39      United States
74            Germany
75            Germany
...               ...
297327          Japan
297339         Greece
297341    Netherlands
297344         Uganda
297348         France

[125071 rows x 1 columns]

In [95]:
df[df['Team']=='Greece']
print(type(df[df['Team']=='Greece']))

<class 'pandas.DataFrame'>

In [96]:
greece_df=df[df['Team']=='Greece'] #Dataframe
greece_years=greece_df['Year'] #Series
df[df['Team']=='Greece']['Year'] #Series

0         1896
2         1896
4         1896
5         1896
6         1896
          ...
296844    2024
296845    2024
297214    2024
297297    2024
297339    2024
Name: Year, Length: 3176, dtype: int64

In [97]:
#duplicates
df.duplicated().sum() #Extract full row duplicates is zero in this dataset

np.int64(0)

* subset=[...] → only these columns decide if two rows are "the same"
* keep=False → flag every row in a duplicate group, not just the extras, so you can inspect them

* keep='first' keeps the first occurrence and drops the rest. keep='last' keeps the most recent instead. 
* Keep=False drops all copies if you don't trust any of them.

* drop_duplicates(subset=['Name']) alone would delete an athlete's second sport entirely Choosing the right subset is the most important decision here.

In [98]:
dup_mask=df.duplicated(subset=['Name','Year','Event'],keep=False) #Extract duplicates based on subset of columns
df[dup_mask].sort_values(['Name','Year']).head(10) #Dataframe of duplicates

,Entry ID,Name,Gender,Age,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List
923,924,A. Dubois,Male,NaN,Gitana-2,FRA,1900,Summer,Paris,Sailing,Sailing Mixed 3-10 Ton,Bronze,NaN,NaN
924,925,A. Dubois,Male,NaN,Gitana-2,FRA,1900,Summer,Paris,Sailing,Sailing Mixed 3-10 Ton,Silver,NaN,NaN
43592,43593,A. Wynne Rogers,Male,NaN,Great Britain,GBR,1948,Summer,London,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN,NaN,NaN
43593,43594,A. Wynne Rogers,Male,NaN,Great Britain,GBR,1948,Summer,London,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN,NaN,NaN
271434,271435,ALI Mohamed,Male,34.0,Bahrain,BRN,2020,Summer,Tokyo,Handball,Men Team,NaN,NaN,NaN
271435,271436,ALI Mohamed,Male,31.0,Bahrain,BRN,2020,Summer,Tokyo,Handball,Men Team,NaN,NaN,NaN
19605,19606,"Aase Lundsteen (-Madsen, -Hoffman-Madsen)",Female,20.0,Denmark,DEN,1924,Summer,Paris,Art Competitions,Art Competitions Mixed Painting,NaN,NaN,NaN
19606,19607,"Aase Lundsteen (-Madsen, -Hoffman-Madsen)",Female,20.0,Denmark,DEN,1924,Summer,Paris,Art Competitions,Art Competitions Mixed Painting,NaN,NaN,NaN
28257,28258,Acee Blue Eagle,Male,24.0,United States,USA,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN,NaN,NaN
28258,28259,Acee Blue Eagle,Male,24.0,United States,USA,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN,NaN,NaN

In [99]:
#String operations (the .str accessor)

#Text data is messy-inconsistent,
#.str lets you apply a text operation to every value in a column at once, and it returns a new Series of the results.
#youc can't just call .lower() on a whole column directly, the way you would on a single string, because the column is a Series, not a string.

df[df['Name'].str.contains('"',na=False)][['Name']].head()

#na=False tells pandas that if any row with missing value is found then treat it as False, no match finds athletes with "" in name
#finds athletes with "" in Name

                                  Name
2   Konstantinos "Kostas" Akratopoulos
3   Konstantinos "Kostas" Akratopoulos
26           Thomas Edmund "Tom" Burke
27           Thomas Edmund "Tom" Burke
40          Thomas Pelham "Tom" Curtis

In [100]:
df['Sport']=df['Sport'].str.strip().str.lower()

In [101]:
df['Team'].unique()        # no .str needed — works on any type
df['Team'].nunique()       # count of distinct values (excludes NaN by default)
df['Medal'].value_counts() # how often each value appears

Medal
Gold      14172
Bronze    14162
Silver    13898
Name: count, dtype: int64

In [102]:
#Rule of thumb: if the operation would make sense on plain numbers too (.unique(), .sort_values(), .isna()), it doesn't need .str. If it only makes sense for text (.lower(), .contains(), .split()), it does.

In [103]:
#Regex
#"Greece-3" - Pull the 3 or the last digit out.

sample=pd.Series(['Greece','Greece-1','Greece-3','United States'])
sample.str.contains(r'\d') #means a "digit", check if one digit exists in the string

0    False
1     True
2     True
3    False
dtype: bool

In [104]:
sample.str.extract(r'(\d)') #pulls out the first digit it finds, if any, and returns a new Series of the results

     0
0  NaN
1    1
2    3
3  NaN

In [105]:
df['team_digit'] = df['Team'].str.extract(r'(\d)').head(15) 
print(type(df['team_digit']))
print(df['team_digit'].head(15))

df[df['team_digit'].notna()][['Team','team_digit']].drop_duplicates() #filter rows where team_digit is not null and show Team and team_digit columns

<class 'pandas.Series'>
0     NaN
1       3
2     NaN
3       3
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
Name: team_digit, dtype: str

       Team team_digit
1  Greece-3          3

In [106]:
#Check one or more digits
sample=pd.Series(['Greece','Greece-1','Greece-3','United States','Greece-33'])
sample.str.contains(r'\d+') #\d+ means one or more digits, check if one or more digits exists in the string

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [107]:
df['team_digit'] = df['Team'].str.extract(r'(\d+)') 
print(type(df['team_digit']))
print(df['team_digit'])

df[df['team_digit'].notna()][['Team','team_digit']].drop_duplicates()

<class 'pandas.Series'>
0         NaN
1           3
2         NaN
3           3
4         NaN
         ...
300261    NaN
300262    NaN
300263    NaN
300264    NaN
300265    NaN
Name: team_digit, Length: 300266, dtype: str

             Team team_digit
1        Greece-3          3
30       Greece-1          1
254      Greece-2          2
391     Martha-27         27
392      Martha-1          1
...           ...        ...
223944     Cuba-1          1
225027     Cuba-2          2
225742  Belarus-2          2
242412   Serbia-2          2
251046   Serbia-1          1

[385 rows x 2 columns]

In [108]:
#To extract letters
names = pd.Series(['Konstantinos "Kostas" Akratopoulos', 'Thomas Edmund "Tom" Burke', 'San "Mary Jane" Smith'])
names.str.extract(r'(\w)')

   0
0  K
1  T
2  S

In [109]:
print(names.str.extract(r'(\w+)'))
print(names.str.extract(r'"(\w+)'))

              0
0  Konstantinos
1        Thomas
2           San
        0
0  Kostas
1     Tom
2    Mary

In [110]:
print(names.str.extract(r'(\w+)'))
print(names.str.extract(r'(\w+\s\w+)'))

print(names.str.extract(r'"(\w+)'))
print(names.str.extract(r'"(\w+\s\w+)'))

              0
0  Konstantinos
1        Thomas
2           San
               0
0            NaN
1  Thomas Edmund
2      Mary Jane
        0
0  Kostas
1     Tom
2    Mary
           0
0        NaN
1        NaN
2  Mary Jane

In [111]:
team1=pd.Series(['Greece','Great Britain','New Greece'])
print(team1.str.contains(r'^Greece')) #Starts with Greece

team2=pd.Series(['Greece','Great Britain','1-Greece'])
print(team2.str.contains(r'\d$')) #Ends with a digit

team3=pd.Series(['Greece-111','Great Britain','1-Greece','Greece-46','Greece-1'])
print(team3.str.contains(r'\d+$')) #Ends with one or more digits

team4=pd.Series(['Greece1','Great Britain','123','G1'])
print(team4.str.contains(r'\D')) #non-digit

team5=pd.Series(['Greece-1','Greece-12','Greece@1','Greece&&12','Greece&&1'])
print(team5.str.contains(r'\D\d$')) #One non digit before ending with exactly one digit

0     True
1    False
2    False
dtype: bool
0    False
1    False
2    False
dtype: bool
0     True
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2    False
3     True
dtype: bool
0     True
1    False
2     True
3    False
4     True
dtype: bool