In [2]:
import pandas as pd
df=pd.read_csv("Datasets/all_athlete_games.csv", low_memory=False)

In [3]:
#Concatenation -pd.concat()

#Concatenation is the simplest way to combine datatframes-it just stacks them either on top of each other (more rows)or side by side (more columns)
#Here there is no matching logic,no keys-it just glues things together based on position.

#axis=0 (stacking vertically,more rows)


#scenario : if we have two separate data files with summer and winter games in each,and if we have to combine them both into one dataset

summer_df=df[df['Season']=='Summer']
winter_df=df[df['Season']=='Winter']

print(summer_df.shape)
print(winter_df.shape)

combined=pd.concat([summer_df,winter_df],axis=0,ignore_index=True)
print(combined.shape)

print(combined)

(248786, 14)
(51480, 14)
(300266, 14)
        Entry ID                                Name  Gender  Age      Team  \
0              1              Aristidis Akratopoulos    Male  NaN    Greece
1              2              Aristidis Akratopoulos    Male  NaN  Greece-3
2              3  Konstantinos "Kostas" Akratopoulos    Male  NaN    Greece
3              4  Konstantinos "Kostas" Akratopoulos    Male  NaN  Greece-3
4              5                  Anastasios Andreou    Male  NaN    Greece
...          ...                                 ...     ...  ...       ...
300261    300262                     ZUMWINKLE Grace  Female  NaN       NaN
300262    300263                         ZUNTE Darta  Female  NaN       NaN
300263    300264                     ZURBAY Anabelle  Female  NaN       NaN
300264    300265                    ZURBRIGGEN Anina  Female  NaN       NaN
300265    300266                        ZUREK Damian    Male  NaN       NaN

        NOC  Year  Season    City      Sport  \
0       GRE  1896  Summer  Athina     Tennis
1       GRE  1896  Summer  Athina     Tennis
2       GRE  1896  Summer  Athina     Tennis
3       GRE  1896  Summer  Athina     Tennis
4       GRE  1896  Summer  Athina  Athletics
...     ...   ...     ...     ...        ...
300261  USA  2026  Winter   Italy        NaN
300262  EST  2026  Winter   Italy        NaN
300263  IRL  2026  Winter   Italy        NaN
300264  BUL  2026  Winter   Italy        NaN
300265  POL  2026  Winter   Italy        NaN

                                     Event Medal Sport Disciplines Event List
0                     Tennis Men's Singles   NaN               NaN        NaN
1                     Tennis Men's Doubles   NaN               NaN        NaN
2                     Tennis Men's Singles   NaN               NaN        NaN
3                     Tennis Men's Doubles   NaN               NaN        NaN
4       Athletics Men's 110 metres Hurdles   NaN               NaN        NaN
...                                    ...   ...               ...        ...
300261                                 NaN   NaN               NaN        NaN
300262                                 NaN   NaN               NaN        NaN
300263                                 NaN   NaN               NaN        NaN
300264                                 NaN   NaN               NaN        NaN
300265                                 NaN   NaN               NaN        NaN

[300266 rows x 14 columns]

In [11]:
#Concatenating rows of dataframes with different columns

core_info=df[['Name','Team','Year']]
extra_info=df[['Name','Medal']]

pd.concat([core_info,extra_info],axis=0).head(50)

#When the columns don't fully match, concat (axis=0) by default keeps every column from both and fills NaN wherever a piece didn't have that column

                                  Name                   Team    Year Medal
0               Aristidis Akratopoulos                 Greece  1896.0   NaN
1               Aristidis Akratopoulos               Greece-3  1896.0   NaN
2   Konstantinos "Kostas" Akratopoulos                 Greece  1896.0   NaN
3   Konstantinos "Kostas" Akratopoulos               Greece-3  1896.0   NaN
4                   Anastasios Andreou                 Greece  1896.0   NaN
5                      Ioannis Andreou                 Greece  1896.0   NaN
6              Nikolaos Andriakopoulos                 Greece  1896.0   NaN
7                     Georgios Anninos                 Greece  1896.0   NaN
8                       Antelothanasis                 Greece  1896.0   NaN
9                    Georgios Aspiotis                 Greece  1896.0   NaN
10                       Edward Battel          Great Britain  1896.0   NaN
11                       Edward Battel          Great Britain  1896.0   NaN
12                       Edward Battel          Great Britain  1896.0   NaN
13                      Albert Baumann            Switzerland  1896.0   NaN
14                    Spyridon Belokas                 Greece  1896.0   NaN
15                Arthur Charles Blake          United States  1896.0   NaN
16                Arthur Charles Blake          United States  1896.0   NaN
17           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
18           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
19           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
20           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
21           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
22           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
23           Conrad Helmut Fritz Bcker                Germany  1896.0   NaN
24               John Mary Pius Boland          Great Britain  1896.0   NaN
25               John Mary Pius Boland  Great Britain/Germany  1896.0   NaN
26           Thomas Edmund "Tom" Burke          United States  1896.0   NaN
27           Thomas Edmund "Tom" Burke          United States  1896.0   NaN
28                  Eugne Henri Callot                 France  1896.0   NaN
29         Demetrius Emmanuel Casdagli                 Greece  1896.0   NaN
30         Demetrius Emmanuel Casdagli               Greece-1  1896.0   NaN
31                    Charles Champaud            Switzerland  1896.0   NaN
32                    Charles Champaud            Switzerland  1896.0   NaN
33                    Charles Champaud            Switzerland  1896.0   NaN
34                Ellery Harding Clark          United States  1896.0   NaN
35                Ellery Harding Clark          United States  1896.0   NaN
36                Ellery Harding Clark          United States  1896.0   NaN
37       James Brendan Bennet Connolly          United States  1896.0   NaN
38       James Brendan Bennet Connolly          United States  1896.0   NaN
39       James Brendan Bennet Connolly          United States  1896.0   NaN
40          Thomas Pelham "Tom" Curtis          United States  1896.0   NaN
41          Thomas Pelham "Tom" Curtis          United States  1896.0   NaN
42                  Evangelos Damaskos                 Greece  1896.0   NaN
43                           Nndor Dni                Hungary  1896.0   NaN
44          Georges Daviel de la Nzire                 France  1896.0   NaN
45                    Henri de Laborde                 France  1896.0   NaN
46                           J. Defert                 France  1896.0   NaN
47               Dimitrios Deligiannis                 Greece  1896.0   NaN
48                  Georgios Diamantis                 Greece  1896.0   NaN
49                  Georgios Diamantis                 Greece  1896.0   NaN

In [12]:
#Concatenating more than two pieces and tagging their source
#concat() takes a list so any number of pieces can be stacked in one call

piece1=df[df['Year']<1950]
piece2=df[(df['Year']>=1950) & (df['Year']<2000)]
piece3=df[df['Year']>=2000]

pd.concat([piece1,piece2,piece3],axis=0,ignore_index=True)

,Entry ID,Name,Gender,Age,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List
0,1,Aristidis Akratopoulos,Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN
1,2,Aristidis Akratopoulos,Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN
2,3,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN
3,4,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN
4,5,Anastasios Andreou,Male,NaN,Greece,GRE,1896,Summer,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300261,300262,ZUMWINKLE Grace,Female,NaN,NaN,USA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN
300262,300263,ZUNTE Darta,Female,NaN,NaN,EST,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN
300263,300264,ZURBAY Anabelle,Female,NaN,NaN,IRL,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN
300264,300265,ZURBRIGGEN Anina,Female,NaN,NaN,BUL,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN
300265,300266,ZUREK Damian,Male,NaN,NaN,POL,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN

In [13]:
#Tagging the Source

summer_df=df[df['Season']=='Summer']
winter_df=df[df['Season']=='Winter']

Tagged=pd.concat([summer_df,winter_df],axis=0,keys=["Summer_source","Winter_source"])
print(Tagged)

                      Entry ID                                Name  Gender  \
Summer_source 0              1              Aristidis Akratopoulos    Male
              1              2              Aristidis Akratopoulos    Male
              2              3  Konstantinos "Kostas" Akratopoulos    Male
              3              4  Konstantinos "Kostas" Akratopoulos    Male
              4              5                  Anastasios Andreou    Male
...                        ...                                 ...     ...
Winter_source 300261    300262                     ZUMWINKLE Grace  Female
              300262    300263                         ZUNTE Darta  Female
              300263    300264                     ZURBAY Anabelle  Female
              300264    300265                    ZURBRIGGEN Anina  Female
              300265    300266                        ZUREK Damian    Male

                      Age      Team  NOC  Year  Season    City      Sport  \
Summer_source 0       NaN    Greece  GRE  1896  Summer  Athina     Tennis
              1       NaN  Greece-3  GRE  1896  Summer  Athina     Tennis
              2       NaN    Greece  GRE  1896  Summer  Athina     Tennis
              3       NaN  Greece-3  GRE  1896  Summer  Athina     Tennis
              4       NaN    Greece  GRE  1896  Summer  Athina  Athletics
...                   ...       ...  ...   ...     ...     ...        ...
Winter_source 300261  NaN       NaN  USA  2026  Winter   Italy        NaN
              300262  NaN       NaN  EST  2026  Winter   Italy        NaN
              300263  NaN       NaN  IRL  2026  Winter   Italy        NaN
              300264  NaN       NaN  BUL  2026  Winter   Italy        NaN
              300265  NaN       NaN  POL  2026  Winter   Italy        NaN

                                                   Event Medal  \
Summer_source 0                     Tennis Men's Singles   NaN
              1                     Tennis Men's Doubles   NaN
              2                     Tennis Men's Singles   NaN
              3                     Tennis Men's Doubles   NaN
              4       Athletics Men's 110 metres Hurdles   NaN
...                                                  ...   ...
Winter_source 300261                                 NaN   NaN
              300262                                 NaN   NaN
              300263                                 NaN   NaN
              300264                                 NaN   NaN
              300265                                 NaN   NaN

                     Sport Disciplines Event List
Summer_source 0                    NaN        NaN
              1                    NaN        NaN
              2                    NaN        NaN
              3                    NaN        NaN
              4                    NaN        NaN
...                                ...        ...
Winter_source 300261               NaN        NaN
              300262               NaN        NaN
              300263               NaN        NaN
              300264               NaN        NaN
              300265               NaN        NaN

[300266 rows x 14 columns]

In [14]:
#Stacking horizontally (More columns)
#Imagine Age came from one file and everything came from another file and both files are in the same row order

core_info=df[['Name','Team','Year']]
age_info=df[['Age']]

sideways=pd.concat([core_info,age_info],axis=1)
print(sideways)

#rows in both the files must be in the same order 
#Only then the combined dataset will be right
#axis=1 needs the same number of rows in the same order
#It does not not throw error it just takes the wrong age as it does not check the data match

                                      Name      Team  Year  Age
0                   Aristidis Akratopoulos    Greece  1896  NaN
1                   Aristidis Akratopoulos  Greece-3  1896  NaN
2       Konstantinos "Kostas" Akratopoulos    Greece  1896  NaN
3       Konstantinos "Kostas" Akratopoulos  Greece-3  1896  NaN
4                       Anastasios Andreou    Greece  1896  NaN
...                                    ...       ...   ...  ...
300261                     ZUMWINKLE Grace       NaN  2026  NaN
300262                         ZUNTE Darta       NaN  2026  NaN
300263                     ZURBAY Anabelle       NaN  2026  NaN
300264                    ZURBRIGGEN Anina       NaN  2026  NaN
300265                        ZUREK Damian       NaN  2026  NaN

[300266 rows x 4 columns]

In [15]:
#Merging --> pd.merge()
#Merge combines two dataframes based on matching values in a shared column ("a key")
#This is like a database join
#This does not care about row order or row count it looks up the correct row to pair with
#This is based on row value 

#Basic merge --> matching on a shared column name

noc_region=pd.DataFrame({
    'NOC':['GRE','USE','FRA','GER','GBR','JPN'],
    'Continent':['Europe','North America','Europe','Europe','Europe','Asia']
})

merged=pd.merge(df,noc_region,on='NOC')
merged[['Name','NOC','Continent']]

#on 'NOC' tells pandas match rows wherever NOC values are equal in both dataframes

                                     Name  NOC Continent
0                  Aristidis Akratopoulos  GRE    Europe
1                  Aristidis Akratopoulos  GRE    Europe
2      Konstantinos "Kostas" Akratopoulos  GRE    Europe
3      Konstantinos "Kostas" Akratopoulos  GRE    Europe
4                      Anastasios Andreou  GRE    Europe
...                                   ...  ...       ...
51498                      YOSHIDA Yukino  JPN      Asia
51499                    YOSHIMURA Sayaka  JPN      Asia
51500                    YOSHINAGA Kazuki  JPN      Asia
51501                       ZILLIOX Elina  FRA    Europe
51502                         ZOBEL David  GER    Europe

[51503 rows x 3 columns]

In [16]:
#When column names don't match

noc_region_v2=pd.DataFrame({
    'country_code':['GRE','USA','FRA'],
    'Continent':['Europe','North America','Europe']
})

merged2=pd.merge(df,noc_region_v2,left_on='NOC',right_on='country_code')
merged2=merged2.drop(columns=['country_code'])
#drop the duplicate column after merge
merged2[['Name','NOC','Continent']]

                                     Name  NOC      Continent
0                  Aristidis Akratopoulos  GRE         Europe
1                  Aristidis Akratopoulos  GRE         Europe
2      Konstantinos "Kostas" Akratopoulos  GRE         Europe
3      Konstantinos "Kostas" Akratopoulos  GRE         Europe
4                      Anastasios Andreou  GRE         Europe
...                                   ...  ...            ...
38003                     WRIGHT Isabella  USA  North America
38004                          YOUNG Jack  USA  North America
38005                       ZILLIOX Elina  FRA         Europe
38006                       ZINGAS Emilea  USA  North America
38007                     ZUMWINKLE Grace  USA  North America

[38008 rows x 3 columns]

In [17]:
#Merging on multiple columns at once
sport_year_notes=pd.DataFrame({
    'Sport':['Athletics','Swimming'],
    'Year':[2000,2000],
    'Note':['High altitude venue','New pool record set']
})

sp=pd.merge(df,sport_year_notes,on=['Sport','Year'])
sp[['Name','Sport','Year','Note','Age','Team']]

,Name,Sport,Year,Note,Age,Team
0,Timo Antero Aaltonen,Athletics,2000,High altitude venue,31.0,Finland
1,Stefan Remco Aartsen,Swimming,2000,New pool record set,25.0,Netherlands
2,Stefan Remco Aartsen,Swimming,2000,New pool record set,25.0,Netherlands
3,Pablo Martn Abal,Swimming,2000,New pool record set,23.0,Argentina
4,Pablo Martn Abal,Swimming,2000,New pool record set,23.0,Argentina
...,...,...,...,...,...,...
4204,Daugvinas Zujus,Athletics,2000,High altitude venue,24.0,Lithuania
4205,Ellina Aleksandrovna Zvereva (Kisheyeva-),Athletics,2000,High altitude venue,39.0,Belarus
4206,"Klaas Erik ""Klaas-Erik"" Zwering",Swimming,2000,New pool record set,19.0,Netherlands
4207,"Klaas Erik ""Klaas-Erik"" Zwering",Swimming,2000,New pool record set,19.0,Netherlands
4208,Olesya Nikolayevna Zykina,Athletics,2000,High altitude venue,19.0,Russia

In [18]:
#merging on index instead of a column

non_region_indexed=pd.DataFrame({
    'Continent':['Europe','North America','Europe']
},
index=['GRE','USA','FRA'])

noc_in=pd.merge(df,non_region_indexed,left_on='NOC',right_index=True)
noc_in[['Name','NOC','Continent']]
#right_index=True says match on right dataframe's index not a named column

                                      Name  NOC      Continent
0                   Aristidis Akratopoulos  GRE         Europe
1                   Aristidis Akratopoulos  GRE         Europe
2       Konstantinos "Kostas" Akratopoulos  GRE         Europe
3       Konstantinos "Kostas" Akratopoulos  GRE         Europe
4                       Anastasios Andreou  GRE         Europe
...                                    ...  ...            ...
300161                     WRIGHT Isabella  USA  North America
300201                          YOUNG Jack  USA  North America
300246                       ZILLIOX Elina  FRA         Europe
300248                       ZINGAS Emilea  USA  North America
300261                     ZUMWINKLE Grace  USA  North America

[38008 rows x 3 columns]

In [19]:
#Suffixes, Handling overlapping non-key column names

extra_data=pd.DataFrame({
    'NOC':['GRE','USA'],
    'Age':[99,99]
})

ed=pd.merge(df,extra_data,on='NOC',suffixes=('_original','_lookup'))
ed.head()

,Entry ID,Name,Gender,Age_original,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List,Age_lookup
0,1,Aristidis Akratopoulos,Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,99
1,2,Aristidis Akratopoulos,Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,99
2,3,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,99
3,4,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,99
4,5,Anastasios Andreou,Male,NaN,Greece,GRE,1896,Summer,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,NaN,NaN,99

In [20]:
#Join types -inner, left, outer, right, cross
from tkinter import TRUE

from numpy import True_


noc_region_partial=pd.DataFrame({'NOC':['GRE','USA','FRA'],
                                'Continent':['Europe','North America','Europe']})

inner=pd.merge(df,noc_region_partial,on='NOC',how='inner',indicator='source')
print(inner[['Name','NOC','Continent']])
print(inner.head())

                                     Name  NOC      Continent
0                  Aristidis Akratopoulos  GRE         Europe
1                  Aristidis Akratopoulos  GRE         Europe
2      Konstantinos "Kostas" Akratopoulos  GRE         Europe
3      Konstantinos "Kostas" Akratopoulos  GRE         Europe
4                      Anastasios Andreou  GRE         Europe
...                                   ...  ...            ...
38003                     WRIGHT Isabella  USA  North America
38004                          YOUNG Jack  USA  North America
38005                       ZILLIOX Elina  FRA         Europe
38006                       ZINGAS Emilea  USA  North America
38007                     ZUMWINKLE Grace  USA  North America

[38008 rows x 3 columns]
   Entry ID                                Name Gender  Age      Team  NOC  \
0         1              Aristidis Akratopoulos   Male  NaN    Greece  GRE
1         2              Aristidis Akratopoulos   Male  NaN  Greece-3  GRE
2         3  Konstantinos "Kostas" Akratopoulos   Male  NaN    Greece  GRE
3         4  Konstantinos "Kostas" Akratopoulos   Male  NaN  Greece-3  GRE
4         5                  Anastasios Andreou   Male  NaN    Greece  GRE

   Year  Season    City      Sport                               Event Medal  \
0  1896  Summer  Athina     Tennis                Tennis Men's Singles   NaN
1  1896  Summer  Athina     Tennis                Tennis Men's Doubles   NaN
2  1896  Summer  Athina     Tennis                Tennis Men's Singles   NaN
3  1896  Summer  Athina     Tennis                Tennis Men's Doubles   NaN
4  1896  Summer  Athina  Athletics  Athletics Men's 110 metres Hurdles   NaN

  Sport Disciplines Event List Continent source
0               NaN        NaN    Europe   both
1               NaN        NaN    Europe   both
2               NaN        NaN    Europe   both
3               NaN        NaN    Europe   both
4               NaN        NaN    Europe   both

In [21]:
print(inner['NOC'].unique())
print(inner.shape)

<StringArray>
['GRE', 'USA', 'FRA']
Length: 3, dtype: str
(38008, 16)

In [22]:
left=pd.merge(df,noc_region_partial,on='NOC',how='left',indicator='source')
print(left['Continent'].isna().sum())
print(left['NOC'].unique())
print(left.shape)
print(left.head())

262258
<StringArray>
['GRE', 'GBR', 'SUI', 'USA', 'GER', 'FRA', 'HUN', 'AUS', 'AUT', 'DEN',
 ...
 'MNE', 'MHL', 'TUV', 'ROT', 'KOS', 'SSD', 'ROC', 'EOR', 'LBN', 'AIN']
Length: 234, dtype: str
(300266, 16)
   Entry ID                                Name Gender  Age      Team  NOC  \
0         1              Aristidis Akratopoulos   Male  NaN    Greece  GRE
1         2              Aristidis Akratopoulos   Male  NaN  Greece-3  GRE
2         3  Konstantinos "Kostas" Akratopoulos   Male  NaN    Greece  GRE
3         4  Konstantinos "Kostas" Akratopoulos   Male  NaN  Greece-3  GRE
4         5                  Anastasios Andreou   Male  NaN    Greece  GRE

   Year  Season    City      Sport                               Event Medal  \
0  1896  Summer  Athina     Tennis                Tennis Men's Singles   NaN
1  1896  Summer  Athina     Tennis                Tennis Men's Doubles   NaN
2  1896  Summer  Athina     Tennis                Tennis Men's Singles   NaN
3  1896  Summer  Athina     Tennis                Tennis Men's Doubles   NaN
4  1896  Summer  Athina  Athletics  Athletics Men's 110 metres Hurdles   NaN

  Sport Disciplines Event List Continent source
0               NaN        NaN    Europe   both
1               NaN        NaN    Europe   both
2               NaN        NaN    Europe   both
3               NaN        NaN    Europe   both
4               NaN        NaN    Europe   both

In [23]:
right=pd.merge(df,noc_region_partial,on='NOC',how='right')
print(right['Continent'].isna().sum())
print(right['NOC'].unique())

outer=pd.merge(df,noc_region_partial,on='NOC',how='outer',indicator=True)
print(outer.head())
print(outer['Continent'].isna().sum())

0
<StringArray>
['GRE', 'USA', 'FRA']
Length: 3, dtype: str
   Entry ID                   Name Gender   Age         Team  NOC  Year  \
0     31423  Jammal-ud-Din Affendi   Male  28.0  Afghanistan  AFG  1936
1     31572          Mohammad Asif   Male  17.0  Afghanistan  AFG  1936
2     31577         Sayed Ali Atta   Male  22.0  Afghanistan  AFG  1936
3     31595    Sayed Mohammad Ayub   Male  27.0  Afghanistan  AFG  1936
4     31596       Sayed Ali Babaci   Male  21.0  Afghanistan  AFG  1936

   Season    City   Sport                Event Medal Sport Disciplines  \
0  Summer  Berlin  Hockey  Hockey Men's Hockey   NaN               NaN
1  Summer  Berlin  Hockey  Hockey Men's Hockey   NaN               NaN
2  Summer  Berlin  Hockey  Hockey Men's Hockey   NaN               NaN
3  Summer  Berlin  Hockey  Hockey Men's Hockey   NaN               NaN
4  Summer  Berlin  Hockey  Hockey Men's Hockey   NaN               NaN

  Event List Continent     _merge
0        NaN       NaN  left_only
1        NaN       NaN  left_only
2        NaN       NaN  left_only
3        NaN       NaN  left_only
4        NaN       NaN  left_only
262258

In [24]:
#Cross Join

seasons=pd.DataFrame({'Season':['Summer','Winter']})
genders=pd.DataFrame({'Gender':['Male','Female']})

Cross=pd.merge(seasons,genders,how='cross')
print(Cross)

   Season  Gender
0  Summer    Male
1  Summer  Female
2  Winter    Male
3  Winter  Female

In [25]:
#.join()- shortcut for index based merging

noc_lookup=pd.DataFrame({'Continent':['Europe','North America']},index=['GRE','USA'])

df.set_index('NOC').join(noc_lookup)

,Entry ID,Name,Gender,Age,Team,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List,Continent
NOC,,,,,,,,,,,,,,
GRE,1,Aristidis Akratopoulos,Male,NaN,Greece,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,Europe
GRE,2,Aristidis Akratopoulos,Male,NaN,Greece-3,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,Europe
GRE,3,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,Europe
GRE,4,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece-3,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,Europe
GRE,5,Anastasios Andreou,Male,NaN,Greece,1896,Summer,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,NaN,NaN,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA,300262,ZUMWINKLE Grace,Female,NaN,NaN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,North America
EST,300263,ZUNTE Darta,Female,NaN,NaN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,NaN
IRL,300264,ZURBAY Anabelle,Female,NaN,NaN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,NaN
BUL,300265,ZURBRIGGEN Anina,Female,NaN,NaN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,NaN
POL,300266,ZUREK Damian,Male,NaN,NaN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
#pd.merge() - Syntaxes
pd.merge(
    left,              # first (left) DataFrame
    right,             # second (right) DataFrame
    how='inner',        # join type
    on=None,             # column(s) to match on, if the name is the SAME in both
    left_on=None,        # column(s) to match on, from the LEFT dataframe
    right_on=None,       # column(s) to match on, from the RIGHT dataframe
    left_index=False,     # match using the LEFT dataframe's index instead of a column
    right_index=False,     # match using the RIGHT dataframe's index instead of a column
    suffixes=('_x', '_y'), # tag for overlapping non-key column names
    indicator=False,        # add a column showing where each row's match came from
    validate=None            # enforce an expected key relationship, error if violated
)

,Entry ID,Name,Gender,Age,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List,Continent,source
0,1,Aristidis Akratopoulos,Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,Europe,both
1,2,Aristidis Akratopoulos,Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,Europe,both
2,3,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,Europe,both
3,4,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,Europe,both
4,5,Anastasios Andreou,Male,NaN,Greece,GRE,1896,Summer,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,NaN,NaN,Europe,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38003,300162,WRIGHT Isabella,Female,NaN,NaN,USA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,North America,both
38004,300202,YOUNG Jack,Male,NaN,NaN,USA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,North America,both
38005,300247,ZILLIOX Elina,Female,NaN,NaN,FRA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,Europe,both
38006,300249,ZINGAS Emilea,Female,NaN,NaN,USA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,North America,both
38007,300262,ZUMWINKLE Grace,Female,NaN,NaN,USA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,North America,both

In [27]:
#validate - one_to_one, one_to_many, many_to_one, many_to_many

#1:1 - error if key is duplicated on either side
#1:m - error if key is duplicated on left side
#m:1 - error if key is duplicated on right side
#m:m - no uniqueness check at all (same as default behaviour even if validate is not written)

pd.merge(df,noc_region,on='NOC',validate='many_to_one')

,Entry ID,Name,Gender,Age,Team,NOC,Year,Season,City,Sport,Event,Medal,Sport Disciplines,Event List,Continent
0,1,Aristidis Akratopoulos,Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,Europe
1,2,Aristidis Akratopoulos,Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,Europe
2,3,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece,GRE,1896,Summer,Athina,Tennis,Tennis Men's Singles,NaN,NaN,NaN,Europe
3,4,"Konstantinos ""Kostas"" Akratopoulos",Male,NaN,Greece-3,GRE,1896,Summer,Athina,Tennis,Tennis Men's Doubles,NaN,NaN,NaN,Europe
4,5,Anastasios Andreou,Male,NaN,Greece,GRE,1896,Summer,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,NaN,NaN,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51498,300199,YOSHIDA Yukino,Female,NaN,NaN,JPN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,Asia
51499,300200,YOSHIMURA Sayaka,Female,NaN,NaN,JPN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,Asia
51500,300201,YOSHINAGA Kazuki,Male,NaN,NaN,JPN,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,Asia
51501,300247,ZILLIOX Elina,Female,NaN,NaN,FRA,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,Europe
51502,300253,ZOBEL David,Male,NaN,NaN,GER,2026,Winter,Italy,NaN,NaN,NaN,NaN,NaN,Europe