## Pandas Selection
### What is selection ?
Selection means retrieving specific rows, columns, or individual values from a DataFrame.

In analysis, we almost never work with an entire dataset at once. Instead we extract only the information required to answer a business question.

Example:
* Show all players from spain.
* Display only the player name and goals
* Find players who scored more than 2 goals

In [1]:
#Setup- Load the dataset

import pandas as pd
#cols=["player_name","nationality","age","player_id","goals","match_date","position","player_rating"]
df=pd.read_csv("./datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"])

df["match_date"]=pd.to_datetime(df["match_date"],format="%d-%m-%Y")

#check the size of the dataset
print(df.shape)
df.head()

(54600, 75)

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

## Four Ways to Select Data

| Method | Description | Use When |
|--------|-------------|----------|
| `[]` | Select one or more columns | You only need columns |
| `.loc[]` | Label-based selection | You know the row labels or column names |
| `.iloc[]` | Position-based selection | You know the row or column positions |
| Boolean Masking / `.query()` | Filter rows using conditions | You want records matching a condition |

In [2]:
#Selecting Columns

#The simplest form of selection is selecting one or more columns

#Selecting a single column
#Syntax: df["column_name"]

player_names=df["player_name"]
print(player_names.head())
print(type(player_names))

#Selecting a single column returns a series,a 1D object,think of it as a single column extracted from a table

0          Rodri Fati
1     Ansu Le Normand
2          Gavi Ramos
3       Pedro Cubarsi
4    Alvaro Oyarzabal
Name: player_name, dtype: str
<class 'pandas.Series'>

In [3]:
#Selecting multiple columns
#Syntax: df[["column1","column2"]]

#Notice the double square brackets

#Outer brackets-tell pandas you're selecting columns'
#Inner brackets-creates a python list containing multiple column names

players = df[[
    "player_name",
    "nationality",
    "position",
    "goals",
    "player_rating"
]]

print(players.head())
print(type(players))

        player_name nationality    position  goals  player_rating
0        Rodri Fati     Spanish  Goalkeeper      0            5.6
1   Ansu Le Normand     Spanish  Midfielder      0            5.7
2        Gavi Ramos     Spanish  Midfielder      1            8.3
3     Pedro Cubarsi     Spanish     Forward      1            6.9
4  Alvaro Oyarzabal     Spanish    Defender      0            5.7
<class 'pandas.DataFrame'>

Use a Series when:
* You need values from one column.
* You want to perform calculations.
* You want to use methods like:

df["goals"].mean()

df["goals"].sum()

df["player_rating"].max()

Use a DataFrame when:
* You want to keep the tabular structure.
* You plan to add more columns later.
* You want to merge or join with another DataFrame.
* You are passing data to functions that expect a DataFrame.

In [4]:
#.loc[]- Label baed selection

#.loc[] is used to select rows and columns using labels

#Labels refers to:
#Roe-index labels
#Column names

#Syntax: df.loc[row_label,column_label]

#Select a single row

print(df.loc[0])

#Select multiple rows
print(df.loc[[0,1,2,3,4]])

player_id                       P00055
player_name                 Rodri Fati
age                                 26
nationality                    Spanish
team                             Spain
                               ...
total_goals_tournament               0
total_assists_tournament             0
total_minutes_tournament           242
player_of_match_awards               0
tournament_rating                  5.8
Name: 0, Length: 75, dtype: object
  player_id       player_name  age nationality   team  jersey number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3
1    P00070   Ansu Le Normand   19     Spanish  Spain             18
2    P00066        Gavi Ramos   18     Spanish  Spain             14
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1
1  Midfielder        178         75          Right  ...               3.5
2  Midfielder        177         72           Left  ...              15.3
3     Forward        182         74          Right  ...               1.2
4    Defender        191         81           Left  ...               6.2

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9              42.0
1                 38.2             43.7              31.1
2                 99.0             99.0              83.4
3                 19.8             42.3              40.9
4                 44.1             33.5              60.0

  clutch_performance_score total_goals_tournament total_assists_tournament  \
0                     51.8                      0                        0
1                     52.7                      0                        3
2                     54.8                      1                        1
3                     78.5                      5                        3
4                     56.6                      0                        0

  total_minutes_tournament player_of_match_awards  tournament_rating
0                      242                      0                5.8
1                      342                      0                5.5
2                      245                      0                8.4
3                      422                      0                6.7
4                      440                      0                5.7

[5 rows x 75 columns]

| Selection | Syntax |
|-----------|--------|
| Single Row | `df.loc[0]` |
| Multiple Rows | `df.loc[[0,1,2]]` |
| Row Range | `df.loc[0:4]` |
| Single Column | `df.loc[:, "player_name"]` |
| Multiple Columns | `df.loc[:, ["player_name","goals"]]` |
| Rows & Columns | `df.loc[0:4, ["player_name","goals"]]` |
| Single Value | `df.loc[2,"player_name"]` |

In [5]:
# Single Row
df.loc[0]

#Multiple Rows
df.loc[[0,1,2]]

#row range
df.loc[0:4]

#Single Column
df.loc[:, "player_name"]

#Multiple Columns
df.loc[:, ["player_name","goals"]]

#Rows & Columns
df.loc[0:4, ["player_name","goals"]]

#Single Value
df.loc[2,"player_name"]

'Gavi Ramos'

### i.loc - position based selection
* iloc[ ] is used to select rows and columns using integer positions.
* Instead of row labels and column names, .iloc[ ] uses the position of rows and columns.
* Row and column positions always start from 0.

### Syntax - df.iloc[row_position, column_position]

### Important Rules
* .iloc[ ] uses positions, not labels.
* Positions always start from 0.
* When slicing, the ending position is NOT included.
* Works exactly like Python list slicing.

| Selection | Syntax |
|-----------|--------|
| First Row | `df.iloc[0]` |
| Multiple Rows | `df.iloc[[0,5,10]]` |
| Row Range | `df.iloc[0:5]` |
| Single Column | `df.iloc[:,1]` |
| Multiple Columns | `df.iloc[:, [1,4,22]]` |
| Rows & Columns | `df.iloc[0:5,[1,4,22]]` |
| Single Value | `df.iloc[2,1]` |
| Last Row | `df.iloc[-1]` |

In [6]:
#Select first row

import pandas as pd
df=pd.read_csv("./datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"])
df["match_date"]=pd.to_datetime(df["match_date"],format="%d-%m-%Y")


#check the size of the dataset
print(df.shape)
df.head()

print(df.iloc[[0]]) #single row
print()
print(df.iloc[[0,5,10]]) #multiple rows
print()
print(df.iloc[0:5]) #range of rows
print()
print(df.iloc[:,1]) #single column
print()
print(df.iloc[:, [1,4,22]]) #multiple column

(54600, 75)
  player_id player_name  age nationality   team  jersey number    position  \
0    P00055  Rodri Fati   26     Spanish  Spain              3  Goalkeeper

   height_cm  weight_kg preferred_foot  ... possession_impact  \
0        195         75           Left  ...               1.1

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9              42.0

  clutch_performance_score total_goals_tournament total_assists_tournament  \
0                     51.8                      0                        0

  total_minutes_tournament player_of_match_awards  tournament_rating
0                      242                      0                5.8

[1 rows x 75 columns]

   player_id     player_name  age nationality   team  jersey number  \
0     P00055      Rodri Fati   26     Spanish  Spain              3
5     P00072       Dani Gavi   21     Spanish  Spain             20
10    P00069  Ferran Cubarsi   24     Spanish  Spain             17

      position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0   Goalkeeper        195         75           Left  ...               1.1
5   Midfielder        181         78          Right  ...              17.0
10  Midfielder        181         81           Left  ...               6.6

    pressure_resistance creativity_score consistency_score  \
0                  44.2             55.9              42.0
5                  65.4             85.8              91.1
10                 43.9             99.0              77.6

   clutch_performance_score total_goals_tournament total_assists_tournament  \
0                      51.8                      0                        0
5                      48.2                      1                        2
10                     76.9                      1                        2

   total_minutes_tournament player_of_match_awards  tournament_rating
0                       242                      0                5.8
5                       332                      0                6.7
10                      403                      0                5.8

[3 rows x 75 columns]

  player_id       player_name  age nationality   team  jersey number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3
1    P00070   Ansu Le Normand   19     Spanish  Spain             18
2    P00066        Gavi Ramos   18     Spanish  Spain             14
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1
1  Midfielder        178         75          Right  ...               3.5
2  Midfielder        177         72           Left  ...              15.3
3     Forward        182         74          Right  ...               1.2
4    Defender        191         81           Left  ...               6.2

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9              42.0
1                 38.2             43.7              31.1
2                 99.0             99.0              83.4
3                 19.8             42.3              40.9
4                 44.1             33.5              60.0

  clutch_performance_score total_goals_tournament total_assists_tournament  \
0                     51.8                      0                        0
1                     52.7                      0                        3
2                     54.8                      1                        1
3                     78.5                      5                        3
4                     56.6                      0                        0

  total_minutes_tournament player_of_match_awards  tournament_rating
0                      242                      0                5.8
1                      342                      0                5.5
2                      245                      0                8.4
3                      422                      0                6.7
4                      440                      0                5.7

[5 rows x 75 columns]

0              Rodri Fati
1         Ansu Le Normand
2              Gavi Ramos
3           Pedro Cubarsi
4        Alvaro Oyarzabal
               ...
54595         Amir Younis
54596    Safaa Al-Khafaji
54597       Ahmed Hussein
54598       Ibrahim Mhawi
54599    Mohannad Hussein
Name: player_name, Length: 54600, dtype: str

            player_name   team  goals
0            Rodri Fati  Spain      0
1       Ansu Le Normand  Spain      0
2            Gavi Ramos  Spain      1
3         Pedro Cubarsi  Spain      1
4      Alvaro Oyarzabal  Spain      0
...                 ...    ...    ...
54595       Amir Younis   Iraq      0
54596  Safaa Al-Khafaji   Iraq      0
54597     Ahmed Hussein   Iraq      0
54598     Ibrahim Mhawi   Iraq      0
54599  Mohannad Hussein   Iraq      0

[54600 rows x 3 columns]

In [7]:
#Pandas Selection (.loc[] & .iloc[])
#Section A - .loc[]
#Q1.Display the row with index label 10.
#Syntax: df.loc[row_label,column_label]
print(df.loc[10])

#Q2.Display rows 15 to 20.
print(df.loc[15:20])

#Q3.Display only the following columns:
#player_name
#nationality
#position
print(df.loc[:, ["player_name","nationality","position"]])

#Q4.Display rows 25 to 30 and only the following columns:
#player_name
#team
#goals
print(df.loc[25:30, ["player_name","team","goals"]])

#Q5.Retrieve the value stored at
#Row label 12
#Column player_rating
print(df.loc[12,"player_rating"])

#Q6.Display all rows but only the columns:
#age
#goals
#assists
print(df.loc[:,["age","goals","assists"]])

#Q7.Display rows 50 to 55 and the columns:
#player_name
#minutes_played
#player_rating
print(df.loc[50:55,["age","goals","assists"]])

#Q8.Retrieve the nationality of the player whose row label is 5.
print(df.loc[5,["nationality","player_name"]])

#Section B – .iloc[]
#Q9.Display the first row.

#Q10.Display the last row.

#Q11.Display rows 20 to 25.

#Q12.Display the first five rows and first four columns.

#Q13.Display the first ten rows and the columns at positions:
#1
#4
#22

#Q14.Retrieve the value at
#Row position 8
#Column position 4

#Q15.Display every 50th row.

#Q16.Display the last five rows.
#Challenge Questions

#Q17.Using .loc(), display rows 100–110 and columns
#player_name
#position
#goals
#assists

#Q18.Using .iloc(), display
#Rows 100–110
#First six colu#mns

#Q19. onlyplayer_name, player_rating for the first 15 rows using .loc()
print(df.loc[0:14,["player_name","player_rating"]])

#Q20.Display the first 15 rows and columns from positions 1 to 5 using .iloc()
print(df.iloc[0:15,1:6])

player_id                           P00069
player_name                 Ferran Cubarsi
age                                     24
nationality                        Spanish
team                                 Spain
                                 ...
total_goals_tournament                   1
total_assists_tournament                 2
total_minutes_tournament               403
player_of_match_awards                   0
tournament_rating                      5.8
Name: 10, Length: 75, dtype: object
   player_id      player_name  age nationality   team  jersey number  \
15    P00062   Marco Carvajal   33     Spanish  Spain             10
16    P00077    Ferran Morata   26     Spanish  Spain             25
17    P00064    Aymeric Yamal   27     Spanish  Spain             12
18    P00061        Ansu Alba   28     Spanish  Spain              9
19    P00068  Alvaro Llorente   19     Spanish  Spain             16
20    P00060       Ferran Pau   35     Spanish  Spain              8

      position  height_cm  weight_kg preferred_foot  ... possession_impact  \
15    Defender        175         73          Right  ...               0.0
16     Forward        188         78          Right  ...               0.0
17    Defender        181         80           Left  ...               0.0
18    Defender        193         83          Right  ...               0.0
19  Midfielder        186         80          Right  ...               0.0
20    Defender        179         72          Right  ...               0.0

    pressure_resistance creativity_score consistency_score  \
15                 55.5             28.4              99.0
16                 59.0             53.7              79.3
17                 55.1             40.2              52.1
18                 87.8             27.8              72.4
19                 80.6             96.9              88.0
20                 47.3             34.3              45.3

   clutch_performance_score total_goals_tournament total_assists_tournament  \
15                     63.4                      0                        1
16                     80.9                      0                        1
17                     51.3                      0                        0
18                     50.4                      1                        1
19                     50.9                      0                        1
20                     44.3                      0                        0

   total_minutes_tournament player_of_match_awards  tournament_rating
15                      291                      0                0.0
16                      357                      0                0.0
17                      261                      0                0.0
18                      209                      0                0.0
19                      281                      0                0.0
20                      167                      0                0.0

[6 rows x 75 columns]
            player_name nationality    position
0            Rodri Fati     Spanish  Goalkeeper
1       Ansu Le Normand     Spanish  Midfielder
2            Gavi Ramos     Spanish  Midfielder
3         Pedro Cubarsi     Spanish     Forward
4      Alvaro Oyarzabal     Spanish    Defender
...                 ...         ...         ...
54595       Amir Younis       Iraqi    Defender
54596  Safaa Al-Khafaji       Iraqi  Midfielder
54597     Ahmed Hussein       Iraqi  Midfielder
54598     Ibrahim Mhawi       Iraqi  Goalkeeper
54599  Mohannad Hussein       Iraqi  Goalkeeper

[54600 rows x 3 columns]
         player_name          team  goals
25       Gavi Morata         Spain      0
26        Lyle Mvala  South Africa      0
27  Sphephelo Mbatha  South Africa      0
28      Percy Mkhize  South Africa      0
29      Mothobi Xoki  South Africa      0
30      Lyle Makgopa  South Africa      1
6.2
       age  goals  assists
0       26      0        0
1       19      0        0
2       18      1        0
3       20      1        1
4       23      0        0
...    ...    ...      ...
54595   28      0        0
54596   20      0        0
54597   26      0        0
54598   30      0        0
54599   27      0        0

[54600 rows x 3 columns]
    age  goals  assists
50   26      0        0
51   32      0        0
52   25      0        0
53   22      0        0
54   26      1        0
55   23      0        0
nationality      Spanish
player_name    Dani Gavi
Name: 5, dtype: str
         player_name  player_rating
0         Rodri Fati            5.6
1    Ansu Le Normand            5.7
2         Gavi Ramos            8.3
3      Pedro Cubarsi            6.9
4   Alvaro Oyarzabal            5.7
5          Dani Gavi            6.6
6      Rodri Laporte            6.7
7          Ansu Fati            6.8
8       Pedro Torres            6.4
9    Gavi Le Normand            6.3
10    Ferran Cubarsi            6.4
11       Marco Mikel            6.6
12       Alvaro Gavi            6.2
13      Rodri Alonso            7.1
14      Gavi Asensio            0.0
         player_name  age nationality   team  jersey number
0         Rodri Fati   26     Spanish  Spain              3
1    Ansu Le Normand   19     Spanish  Spain             18
2         Gavi Ramos   18     Spanish  Spain             14
3      Pedro Cubarsi   20     Spanish  Spain             21
4   Alvaro Oyarzabal   23     Spanish  Spain              7
5          Dani Gavi   21     Spanish  Spain             20
6      Rodri Laporte   27     Spanish  Spain              6
7          Ansu Fati   27     Spanish  Spain             26
8       Pedro Torres   24     Spanish  Spain              4
9    Gavi Le Normand   25     Spanish  Spain             22
10    Ferran Cubarsi   24     Spanish  Spain             17
11       Marco Mikel   18     Spanish  Spain             19
12       Alvaro Gavi   28     Spanish  Spain             24
13      Rodri Alonso   25     Spanish  Spain             15
14      Gavi Asensio   22     Spanish  Spain              5

In [8]:
print(df.iloc[0:15,1:6])

         player_name  age nationality   team  jersey number
0         Rodri Fati   26     Spanish  Spain              3
1    Ansu Le Normand   19     Spanish  Spain             18
2         Gavi Ramos   18     Spanish  Spain             14
3      Pedro Cubarsi   20     Spanish  Spain             21
4   Alvaro Oyarzabal   23     Spanish  Spain              7
5          Dani Gavi   21     Spanish  Spain             20
6      Rodri Laporte   27     Spanish  Spain              6
7          Ansu Fati   27     Spanish  Spain             26
8       Pedro Torres   24     Spanish  Spain              4
9    Gavi Le Normand   25     Spanish  Spain             22
10    Ferran Cubarsi   24     Spanish  Spain             17
11       Marco Mikel   18     Spanish  Spain             19
12       Alvaro Gavi   28     Spanish  Spain             24
13      Rodri Alonso   25     Spanish  Spain             15
14      Gavi Asensio   22     Spanish  Spain              5

In [9]:
#Boolean masking

#Boolean masking is used to filter rows based on one or more conditions.
#Instead of selecting rows by their labels or positions, we select rows that satisfy a condition.

#For example:
#1. Display players who scored more than 2 goals
#2. Show all spanish players
#3. Find players with a rating greater than 8
#4. Display goalkeepers

In [10]:
#Boolean masking is done in two steps

#Step1: Create a boolean mask

mask=df["goals"]>0
print(mask.head())

#Step2: Apply the boolean mask
scorers=df[mask]
print(scorers.head())

#printing as mask directly
mask=df["goals"]>0
print(df[mask].head())

#Even more direct method
print(df[df["goals"]>0].head())

0    False
1    False
2     True
3     True
4    False
Name: goals, dtype: bool
   player_id    player_name  age    nationality          team  jersey number  \
2     P00066     Gavi Ramos   18        Spanish         Spain             14
3     P00073  Pedro Cubarsi   20        Spanish         Spain             21
7     P00078      Ansu Fati   27        Spanish         Spain             26
30    P01228   Lyle Makgopa   27  South African  South Africa              6
31    P01239  Ronwen Mkhize   26  South African  South Africa             17

      position  height_cm  weight_kg preferred_foot  ... possession_impact  \
2   Midfielder        177         72           Left  ...              15.3
3      Forward        182         74          Right  ...               1.2
7      Forward        182         72          Right  ...               2.4
30    Defender        181         72          Right  ...               9.2
31  Midfielder        183         74          Right  ...              15.3

    pressure_resistance creativity_score consistency_score  \
2                  99.0             99.0              83.4
3                  19.8             42.3              40.9
7                  48.2             35.6              60.9
30                 65.0             24.3              75.5
31                 99.0             68.7              99.0

   clutch_performance_score total_goals_tournament total_assists_tournament  \
2                      54.8                      1                        1
3                      78.5                      5                        3
7                      60.4                      2                        1
30                     70.1                      1                        0
31                     50.2                      1                        0

   total_minutes_tournament player_of_match_awards  tournament_rating
2                       245                      0                8.4
3                       422                      0                6.7
7                       191                      0                6.8
30                      253                      1                6.0
31                      279                      0                6.7

[5 rows x 75 columns]
   player_id    player_name  age    nationality          team  jersey number  \
2     P00066     Gavi Ramos   18        Spanish         Spain             14
3     P00073  Pedro Cubarsi   20        Spanish         Spain             21
7     P00078      Ansu Fati   27        Spanish         Spain             26
30    P01228   Lyle Makgopa   27  South African  South Africa              6
31    P01239  Ronwen Mkhize   26  South African  South Africa             17

      position  height_cm  weight_kg preferred_foot  ... possession_impact  \
2   Midfielder        177         72           Left  ...              15.3
3      Forward        182         74          Right  ...               1.2
7      Forward        182         72          Right  ...               2.4
30    Defender        181         72          Right  ...               9.2
31  Midfielder        183         74          Right  ...              15.3

    pressure_resistance creativity_score consistency_score  \
2                  99.0             99.0              83.4
3                  19.8             42.3              40.9
7                  48.2             35.6              60.9
30                 65.0             24.3              75.5
31                 99.0             68.7              99.0

   clutch_performance_score total_goals_tournament total_assists_tournament  \
2                      54.8                      1                        1
3                      78.5                      5                        3
7                      60.4                      2                        1
30                     70.1                      1                        0
31                     50.2                      1                        0

   total_minutes_tournament player_of_match_awards  tournament_rating
2                       245                      0                8.4
3                       422                      0                6.7
7                       191                      0                6.8
30                      253                      1                6.0
31                      279                      0                6.7

[5 rows x 75 columns]
   player_id    player_name  age    nationality          team  jersey number  \
2     P00066     Gavi Ramos   18        Spanish         Spain             14
3     P00073  Pedro Cubarsi   20        Spanish         Spain             21
7     P00078      Ansu Fati   27        Spanish         Spain             26
30    P01228   Lyle Makgopa   27  South African  South Africa              6
31    P01239  Ronwen Mkhize   26  South African  South Africa             17

      position  height_cm  weight_kg preferred_foot  ... possession_impact  \
2   Midfielder        177         72           Left  ...              15.3
3      Forward        182         74          Right  ...               1.2
7      Forward        182         72          Right  ...               2.4
30    Defender        181         72          Right  ...               9.2
31  Midfielder        183         74          Right  ...              15.3

    pressure_resistance creativity_score consistency_score  \
2                  99.0             99.0              83.4
3                  19.8             42.3              40.9
7                  48.2             35.6              60.9
30                 65.0             24.3              75.5
31                 99.0             68.7              99.0

   clutch_performance_score total_goals_tournament total_assists_tournament  \
2                      54.8                      1                        1
3                      78.5                      5                        3
7                      60.4                      2                        1
30                     70.1                      1                        0
31                     50.2                      1                        0

   total_minutes_tournament player_of_match_awards  tournament_rating
2                       245                      0                8.4
3                       422                      0                6.7
7                       191                      0                6.8
30                      253                      1                6.0
31                      279                      0                6.7

[5 rows x 75 columns]

In [11]:
#Players younger than 21
print(df[df["age"]<21].head())

#Spanish players
print(df[df["nationality"]=="Spanish"].head())

#Players who are not goal keepers
print(df[df["position"]!="goalkeeper"].head())
print(df[~(df["position"]=="goalkeeper")].head())

#Multiple Conditions
#Players who are spanish and have goals>0
print(df[(df["nationality"]=="Spanish") & (df["goals"]>0)])

#Players who have either goals>0 or assists>0
print(df[(df["assists"]>0) | (df["goals"]>0)])

#Players who are spanish, brazzilian or french
print(df[(df["nationality"]=="Spanish") | (df["nationality"]=="Brazilian") | (df["nationality"]=="French")])
print(df[df["nationality"].isin(["Spanish","Brazilian","French"])])

   player_id      player_name  age nationality   team  jersey number  \
1     P00070  Ansu Le Normand   19     Spanish  Spain             18
2     P00066       Gavi Ramos   18     Spanish  Spain             14
3     P00073    Pedro Cubarsi   20     Spanish  Spain             21
11    P00071      Marco Mikel   18     Spanish  Spain             19
19    P00068  Alvaro Llorente   19     Spanish  Spain             16

      position  height_cm  weight_kg preferred_foot  ... possession_impact  \
1   Midfielder        178         75          Right  ...               3.5
2   Midfielder        177         72           Left  ...              15.3
3      Forward        182         74          Right  ...               1.2
11  Midfielder        183         70          Right  ...               2.7
19  Midfielder        186         80          Right  ...               0.0

    pressure_resistance creativity_score consistency_score  \
1                  38.2             43.7              31.1
2                  99.0             99.0              83.4
3                  19.8             42.3              40.9
11                 75.4             60.9              79.9
19                 80.6             96.9              88.0

   clutch_performance_score total_goals_tournament total_assists_tournament  \
1                      52.7                      0                        3
2                      54.8                      1                        1
3                      78.5                      5                        3
11                     63.2                      0                        2
19                     50.9                      0                        1

   total_minutes_tournament player_of_match_awards  tournament_rating
1                       342                      0                5.5
2                       245                      0                8.4
3                       422                      0                6.7
11                      391                      0                7.4
19                      281                      0                0.0

[5 rows x 75 columns]
  player_id       player_name  age nationality   team  jersey number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3
1    P00070   Ansu Le Normand   19     Spanish  Spain             18
2    P00066        Gavi Ramos   18     Spanish  Spain             14
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1
1  Midfielder        178         75          Right  ...               3.5
2  Midfielder        177         72           Left  ...              15.3
3     Forward        182         74          Right  ...               1.2
4    Defender        191         81           Left  ...               6.2

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9              42.0
1                 38.2             43.7              31.1
2                 99.0             99.0              83.4
3                 19.8             42.3              40.9
4                 44.1             33.5              60.0

  clutch_performance_score total_goals_tournament total_assists_tournament  \
0                     51.8                      0                        0
1                     52.7                      0                        3
2                     54.8                      1                        1
3                     78.5                      5                        3
4                     56.6                      0                        0

  total_minutes_tournament player_of_match_awards  tournament_rating
0                      242                      0                5.8
1                      342                      0                5.5
2                      245                      0                8.4
3                      422                      0                6.7
4                      440                      0                5.7

[5 rows x 75 columns]
  player_id       player_name  age nationality   team  jersey number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3
1    P00070   Ansu Le Normand   19     Spanish  Spain             18
2    P00066        Gavi Ramos   18     Spanish  Spain             14
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1
1  Midfielder        178         75          Right  ...               3.5
2  Midfielder        177         72           Left  ...              15.3
3     Forward        182         74          Right  ...               1.2
4    Defender        191         81           Left  ...               6.2

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9              42.0
1                 38.2             43.7              31.1
2                 99.0             99.0              83.4
3                 19.8             42.3              40.9
4                 44.1             33.5              60.0

  clutch_performance_score total_goals_tournament total_assists_tournament  \
0                     51.8                      0                        0
1                     52.7                      0                        3
2                     54.8                      1                        1
3                     78.5                      5                        3
4                     56.6                      0                        0

  total_minutes_tournament player_of_match_awards  tournament_rating
0                      242                      0                5.8
1                      342                      0                5.5
2                      245                      0                8.4
3                      422                      0                6.7
4                      440                      0                5.7

[5 rows x 75 columns]
  player_id       player_name  age nationality   team  jersey number  \
0    P00055        Rodri Fati   26     Spanish  Spain              3
1    P00070   Ansu Le Normand   19     Spanish  Spain             18
2    P00066        Gavi Ramos   18     Spanish  Spain             14
3    P00073     Pedro Cubarsi   20     Spanish  Spain             21
4    P00059  Alvaro Oyarzabal   23     Spanish  Spain              7

     position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0  Goalkeeper        195         75           Left  ...               1.1
1  Midfielder        178         75          Right  ...               3.5
2  Midfielder        177         72           Left  ...              15.3
3     Forward        182         74          Right  ...               1.2
4    Defender        191         81           Left  ...               6.2

   pressure_resistance creativity_score consistency_score  \
0                 44.2             55.9              42.0
1                 38.2             43.7              31.1
2                 99.0             99.0              83.4
3                 19.8             42.3              40.9
4                 44.1             33.5              60.0

  clutch_performance_score total_goals_tournament total_assists_tournament  \
0                     51.8                      0                        0
1                     52.7                      0                        3
2                     54.8                      1                        1
3                     78.5                      5                        3
4                     56.6                      0                        0

  total_minutes_tournament player_of_match_awards  tournament_rating
0                      242                      0                5.8
1                      342                      0                5.5
2                      245                      0                8.4
3                      422                      0                6.7
4                      440                      0                5.7

[5 rows x 75 columns]
      player_id      player_name  age nationality   team  jersey number  \
2        P00066       Gavi Ramos   18     Spanish  Spain             14
3        P00073    Pedro Cubarsi   20     Spanish  Spain             21
7        P00078        Ansu Fati   27     Spanish  Spain             26
653      P00077    Ferran Morata   26     Spanish  Spain             25
4811     P00077    Ferran Morata   26     Spanish  Spain             25
4815     P00072        Dani Gavi   21     Spanish  Spain             20
4816     P00074  Gavi Le Normand   25     Spanish  Spain             22
4817     P00062   Marco Carvajal   33     Spanish  Spain             10
4922     P00074  Gavi Le Normand   25     Spanish  Spain             22
4924     P00073    Pedro Cubarsi   20     Spanish  Spain             21
5280     P00072        Dani Gavi   21     Spanish  Spain             20
5281     P00057     Gavi Asensio   22     Spanish  Spain              5
5621     P00077    Ferran Morata   26     Spanish  Spain             25
5623     P00078        Ansu Fati   27     Spanish  Spain             26
6657     P00076      Alvaro Gavi   28     Spanish  Spain             24
10661    P00067     Rodri Alonso   25     Spanish  Spain             15
10668    P00075      Rodri Mikel   25     Spanish  Spain             23
11572    P00076      Alvaro Gavi   28     Spanish  Spain             24
13783    P00078        Ansu Fati   27     Spanish  Spain             26
13913    P00075      Rodri Mikel   25     Spanish  Spain             23
14276    P00076      Alvaro Gavi   28     Spanish  Spain             24
14284    P00078        Ansu Fati   27     Spanish  Spain             26
14509    P00068  Alvaro Llorente   19     Spanish  Spain             16
16776    P00073    Pedro Cubarsi   20     Spanish  Spain             21
21407    P00065   Pedro Riquelme   24     Spanish  Spain             13
21798    P00075      Rodri Mikel   25     Spanish  Spain             23
24990    P00069   Ferran Cubarsi   24     Spanish  Spain             17
24991    P00065   Pedro Riquelme   24     Spanish  Spain             13
24992    P00077    Ferran Morata   26     Spanish  Spain             25
24995    P00072        Dani Gavi   21     Spanish  Spain             20
26010    P00063      Dani Garcia   28     Spanish  Spain             11
26132    P00067     Rodri Alonso   25     Spanish  Spain             15
27800    P00067     Rodri Alonso   25     Spanish  Spain             15
27825    P00070  Ansu Le Normand   19     Spanish  Spain             18
27829    P00068  Alvaro Llorente   19     Spanish  Spain             16
27832    P00074  Gavi Le Normand   25     Spanish  Spain             22
29459    P00065   Pedro Riquelme   24     Spanish  Spain             13
29463    P00078        Ansu Fati   27     Spanish  Spain             26
29470    P00070  Ansu Le Normand   19     Spanish  Spain             18
30972    P00076      Alvaro Gavi   28     Spanish  Spain             24
31781    P00075      Rodri Mikel   25     Spanish  Spain             23
31782    P00077    Ferran Morata   26     Spanish  Spain             25
34222    P00076      Alvaro Gavi   28     Spanish  Spain             24
34223    P00061        Ansu Alba   28     Spanish  Spain              9
34348    P00074  Gavi Le Normand   25     Spanish  Spain             22
36384    P00075      Rodri Mikel   25     Spanish  Spain             23
37468    P00073    Pedro Cubarsi   20     Spanish  Spain             21
37475    P00069   Ferran Cubarsi   24     Spanish  Spain             17
42516    P00076      Alvaro Gavi   28     Spanish  Spain             24
42727    P00077    Ferran Morata   26     Spanish  Spain             25
42885    P00077    Ferran Morata   26     Spanish  Spain             25
48231    P00075      Rodri Mikel   25     Spanish  Spain             23
49562    P00071      Marco Mikel   18     Spanish  Spain             19
49567    P00065   Pedro Riquelme   24     Spanish  Spain             13
49820    P00056     Pedro Torres   24     Spanish  Spain              4
49823    P00057     Gavi Asensio   22     Spanish  Spain              5
49824    P00072        Dani Gavi   21     Spanish  Spain             20

         position  height_cm  weight_kg preferred_foot  ... possession_impact  \
2      Midfielder        177         72           Left  ...              15.3
3         Forward        182         74          Right  ...               1.2
7         Forward        182         72          Right  ...               2.4
653       Forward        188         78          Right  ...               6.3
4811      Forward        188         78          Right  ...               8.4
4815   Midfielder        181         78          Right  ...              11.6
4816      Forward        172         70          Right  ...               4.4
4817     Defender        175         73          Right  ...               6.7
4922      Forward        172         70          Right  ...               4.6
4924      Forward        182         74          Right  ...               1.3
5280   Midfielder        181         78          Right  ...              16.9
5281     Defender        187         76          Right  ...               3.8
5621      Forward        188         78          Right  ...               4.3
5623      Forward        182         72          Right  ...               1.9
6657      Forward        183         75          Right  ...               6.2
10661  Midfielder        183         78          Right  ...               3.4
10668     Forward        173         73          Right  ...               3.1
11572     Forward        183         75          Right  ...               4.8
13783     Forward        182         72          Right  ...               1.3
13913     Forward        173         73          Right  ...               6.7
14276     Forward        183         75          Right  ...               5.3
14284     Forward        182         72          Right  ...               3.8
14509  Midfielder        186         80          Right  ...              19.4
16776     Forward        182         74          Right  ...               0.8
21407  Midfielder        171         67          Right  ...               4.6
21798     Forward        173         73          Right  ...               5.5
24990  Midfielder        181         81           Left  ...               5.8
24991  Midfielder        171         67          Right  ...               3.5
24992     Forward        188         78          Right  ...               4.0
24995  Midfielder        181         78          Right  ...              15.5
26010    Defender        183         80          Right  ...               3.4
26132  Midfielder        183         78          Right  ...               4.8
27800  Midfielder        183         78          Right  ...               3.0
27825  Midfielder        178         75          Right  ...               3.7
27829  Midfielder        186         80          Right  ...              18.3
27832     Forward        172         70          Right  ...               1.9
29459  Midfielder        171         67          Right  ...               6.4
29463     Forward        182         72          Right  ...               1.8
29470  Midfielder        178         75          Right  ...               0.6
30972     Forward        183         75          Right  ...               6.0
31781     Forward        173         73          Right  ...               3.4
31782     Forward        188         78          Right  ...               5.8
34222     Forward        183         75          Right  ...               4.3
34223    Defender        193         83          Right  ...              11.3
34348     Forward        172         70          Right  ...              10.4
36384     Forward        173         73          Right  ...               3.3
37468     Forward        182         74          Right  ...               2.0
37475  Midfielder        181         81           Left  ...               5.6
42516     Forward        183         75          Right  ...               4.1
42727     Forward        188         78          Right  ...               3.4
42885     Forward        188         78          Right  ...               1.5
48231     Forward        173         73          Right  ...               2.4
49562  Midfielder        183         70          Right  ...               9.2
49567  Midfielder        171         67          Right  ...               1.9
49820    Defender        176         78           Left  ...               7.7
49823    Defender        187         76          Right  ...               2.5
49824  Midfielder        181         78          Right  ...              18.9

       pressure_resistance creativity_score consistency_score  \
2                     99.0             99.0              83.4
3                     19.8             42.3              40.9
7                     48.2             35.6              60.9
653                   68.5             63.0              83.1
4811                  55.2             45.1              66.7
4815                  95.1             99.0              99.0
4816                  99.0             96.4              95.4
4817                  68.6             34.6              87.3
4922                  79.2             84.6              66.6
4924                  34.1             43.3              55.1
5280                  70.7             62.0              98.6
5281                  59.3             32.0              54.6
5621                  59.3             65.3              64.7
5623                  46.8             59.1              57.0
6657                  58.6             89.5              53.9
10661                 33.6             46.7              46.2
10668                 76.4             65.3              61.7
11572                 42.3             68.8              74.4
13783                 33.6             30.5              47.8
13913                 52.0             37.6              76.5
14276                 66.1             53.7              83.1
14284                 37.1             46.4              39.3
14509                 80.1             68.6              99.0
16776                 49.7             37.2              47.4
21407                 45.6             52.0              37.7
21798                 37.4             41.8              67.0
24990                 67.1             77.7              66.4
24991                 42.4             30.1              56.5
24992                 47.1             58.1              67.4
24995                 72.8             85.1              99.0
26010                 43.1             14.3              40.0
26132                 28.5             56.7              48.7
27800                 54.4             27.3              42.7
27825                 30.0             44.3              44.0
27829                 99.0             88.3              82.1
27832                 75.6             67.8              65.5
29459                 40.7             54.9              42.3
29463                 29.8             53.9              62.0
29470                 48.7             39.9              34.3
30972                 70.6             70.5              70.6
31781                 54.8             37.7              65.1
31782                 54.1             66.2              65.9
34222                 83.5             85.9              76.2
34223                 83.7             28.5              97.9

In [12]:
#Selecting columns after filtering
#Display columns --> player name, goals, player rating whose goals>0
print(df.loc[df["goals"]>0,["player_name","goals","player_rating"]])

             player_name  goals  player_rating
2             Gavi Ramos      1            8.3
3          Pedro Cubarsi      1            6.9
7              Ansu Fati      1            6.8
30          Lyle Makgopa      1            6.5
31         Ronwen Mkhize      1            6.3
...                  ...    ...            ...
54498   Nemanja Jevtovic      1            7.8
54558          Pape Sarr      1            7.1
54577    Mohannad Majeed      1            6.0
54582      Mustafa Natiq      1            5.6
54587  Mohannad Al-Saadi      1            6.7

[2743 rows x 3 columns]

In [13]:
#More examples on boolean masking with .loc
# Spanish players who scored — show name, goals, rating
df.loc[
    (df["nationality"] == "Spanish") & (df["goals"] > 0),
    ["player_name", "goals", "player_rating"]
].head()

# Players rated above 8 who played 90 minutes — show name, position, rating
df.loc[
    (df["player_rating"] >= 8.0) & (df["minutes_played"] == 90),
    ["player_name", "position", "player_rating", "minutes_played"]
].head()

# Forwards who scored more than 1 goal — show name, goals, assists
df.loc[
    (df["position"] == "Forward") & (df["goals"] > 1),
    ["player_name", "goals", "assists"]
].head()

# Players under 21 — show name, age, nationality, position
df.loc[
    df["age"] < 21,
    ["player_name", "age", "nationality", "position"]
].head()

# Players with yellow card — show name, nationality, yellow_cards
df.loc[
    df["yellow_cards"] > 0,
    ["player_name", "nationality", "yellow_cards"]
].head()

        player_name    nationality  yellow_cards
9   Gavi Le Normand        Spanish             1
10   Ferran Cubarsi        Spanish             1
20       Ferran Pau        Spanish             1
31    Ronwen Mkhize  South African             1
34      Themba Xoki  South African             1

In [14]:
#Boolean Mask with .iloc[]

#.iloc[] only accepts integer positions — not column names. So you can use a boolean mask for rows but must use integer positions for columns.

In [15]:
# Boolean mask for rows — integer positions for columns
mask   = df["goals"] > 0
result = df.iloc[mask.values, [1, 3, 27, 61]]   # columns by position
#or
result = df.iloc[(df["goals"]>0).values, [1, 3, 27, 61]]   # columns by position
print(result.head())

      player_name    nationality  expected_assists_xa  player_rating
2      Gavi Ramos        Spanish                 0.07            8.3
3   Pedro Cubarsi        Spanish                 0.21            6.9
7       Ansu Fati        Spanish                 0.00            6.8
30   Lyle Makgopa  South African                 0.00            6.5
31  Ronwen Mkhize  South African                 0.00            6.3

In [16]:
# Example 1 — Single condition, multiple columns
# Players who got a red card
df.loc[
    df["red_cards"] > 0,
    ["player_name", "nationality", "position", "red_cards"]
]

# Example 2 — Two conditions, range of columns
# Spanish midfielders
df.loc[
    (df["nationality"] == "Spanish") & (df["position"] == "Midfielder"),
    "player_name":"position"    # column range
]

# Example 3 — Three conditions, specific columns
# Young players under 21 who scored and got high rating
df.loc[
    (df["age"] < 21) & (df["goals"] > 0) & (df["player_rating"] >= 7.0),
    ["player_name", "age", "goals", "player_rating"]
]

# Example 4 — OR condition with columns
# Players who scored OR assisted in Final stage
df.loc[
    ((df["goals"] > 0) | (df["assists"] > 0)) & (df["tournament_stage"] == "Final"),
    ["player_name", "tournament_stage", "goals", "assists"]
]

# Example 5 — NOT condition with columns
# Non-goalkeepers who played full 90 minutes
df.loc[
    (~(df["position"] == "Goalkeeper")) & (df["minutes_played"] == 90),
    ["player_name", "position", "minutes_played", "player_rating"]
]

# Example 6 — isin() with columns
# Players from top nations in knockout stages
knockout_stages = ["Quarter-Final", "Semi-Final", "Final"]
top_nations     = ["Spanish", "Brazilian", "French", "German"]

df.loc[
    (df["tournament_stage"].isin(knockout_stages)) &
    (df["nationality"].isin(top_nations)),
    ["player_name", "nationality", "tournament_stage", "goals"]
]

# Example 7 — str.contains() with columns
# Players with "Gavi" in name — show all performance columns
df.loc[
    df["player_name"].str.contains("Gavi"),
    ["player_name", "nationality", "goals", "assists", "player_rating"]
]

# Example 8 — Multiple conditions with column range
# High rated players in Group Stage
df.loc[
    (df["player_rating"] >= 8.5) & (df["tournament_stage"] == "Group Stage"),
    "player_name":"position"
]

,player_name,age,nationality,team,jersey number,position
1960,Firas Al-Yami,22,Saudi,Saudi Arabia,14,Midfielder
3211,Oleksandr Bondarenko,18,Ukrainian,Ukraine,22,Forward
3928,Lorenzo Frascati,20,Italian,Italy,10,Defender
4167,Saleh Al-Qahtani,23,Saudi,Saudi Arabia,23,Forward
5465,John Armstrong,26,Scottish,Scotland,15,Midfielder
6435,Patrick Vargas,20,Costa Rican,Costa Rica,19,Midfielder
7472,Rasmus Wind,19,Danish,Denmark,26,Forward
8925,Houssem Mokrani,24,Algerian,Algeria,17,Midfielder
9181,Sam James,28,Canadian,Canada,19,Midfielder
9339,Hidajat Ghoddos,24,Iranian,Iran,25,Forward
12958,Vinicius Nunes,23,Brazilian,Brazil,22,Forward
13131,Jesus Reyes,26,Mexican,Mexico,17,Midfielder
13319,Kasey Hector,21,Jamaican,Jamaica,26,Forward
14282,Dani Gavi,21,Spanish,Spain,20,Midfielder
14589,Sebastian Pellerano,32,Ecuadorian,Ecuador,18,Midfielder
14781,Pape Sarr,27,Senegalese,Senegal,26,Forward
15556,Yassine El Yamiq,19,Moroccan,Morocco,17,Midfielder
16701,Wilfred Iheanacho,25,Nigerian,Nigeria,15,Midfielder
17171,Ali Ali,25,Qatari,Qatar,20,Midfielder
17706,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper
17712,Ahmed Moutan,26,Iraqi,Iraq,11,Defender
17717,Mohannad Majeed,18,Iraqi,Iraq,21,Forward
18203,Kevin Saelemaekers,32,Belgian,Belgium,21,Forward
19354,Cody de Jong,25,Dutch,Netherlands,14,Midfielder
20731,Diego Vina,34,Uruguayan,Uruguay,11,Defender
21017,Samuel Uzoho,19,Nigerian,Nigeria,14,Midfielder
21124,Vincent Choupo-Moting,25,Cameroonian,Cameroon,24,Forward
21409,Gavi Ramos,18,Spanish,Spain,14,Midfielder
22079,Kevin Saelemaekers,32,Belgian,Belgium,21,Forward
22453,Vincent Choupo-Moting,25,Cameroonian,Cameroon,24,Forward
22906,Bryan Duarte,28,Costa Rican,Costa Rica,3,Goalkeeper
23356,Jackson Vukovic,24,Australian,Australia,23,Forward
24363,Hakim Ezzalzouli,26,Moroccan,Morocco,9,Defender
24677,Jordan Issahaku,25,Ghanaian,Ghana,23,Forward
25039,Gary Villanueva,26,Chilean,Chile,15,Midfielder
25619,Vinicius Nunes,23,Brazilian,Brazil,22,Forward
26184,Patrick Vargas,20,Costa Rican,Costa Rica,19,Midfielder
28426,Anibal Sanchez,26,Panamanian,Panama,21,Forward
28816,Marcus Chilwell,32,English,England,18,Midfielder
29179,Paolo Gonzalez,27,Peruvian,Peru,21,Forward
29927,Anibal Sanchez,26,Panamanian,Panama,21,Forward

In [17]:
#Querying
#.query()- string based filtering

#.query is a clean way to filter rows using a string expression instead of boolean masking.
#Easier to read especially for multiple conditions

#Syntax: df.query("condition")

#Goals greater than zero
df.query("goals>0")

#Age less than or equal to 21
df.query("age<=21")

#Specific nationality
df.query("nationality=='Spanish'")

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49837,P00076,Alvaro Gavi,28,Spanish,Spain,24,Forward,183,75,Right,...,0.0,69.0,48.3,68.9,58.8,1,0,162,0,0.0
49838,P00064,Aymeric Yamal,27,Spanish,Spain,12,Defender,181,80,Left,...,0.0,63.2,29.2,46.2,64.6,0,0,134,0,0.0
49839,P00058,Rodri Laporte,27,Spanish,Spain,6,Defender,188,80,Right,...,0.0,59.4,36.3,84.7,72.8,0,1,364,0,0.0
49840,P00054,Gavi Morata,27,Spanish,Spain,2,Goalkeeper,190,75,Left,...,0.0,50.8,42.9,41.6,63.0,0,0,284,0,0.0
49841,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,0.0,46.5,19.8,34.8,39.6,0,0,248,0,0.0

In [18]:
#goals>0 and nationality is spanish
df.query("goals>0 & nationality=='Spanish'")
df.query("goals>0 and nationality=='Spanish'")

#goals>0 and assists>0
df.query("goals>0 | assists>0")
df.query("goals>0 or assists>0")

#Combined
df.query("goals>0 and assists>0 and player_rating>=7.0")

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
84,P00153,Memphis Zerrouki,25,Dutch,Netherlands,23,Forward,166,71,Right,...,15.5,91.4,98.5,99.0,75.0,2,1,165,0,8.4
392,P00455,Andrew Ferguson,26,Scottish,Scotland,13,Midfielder,180,74,Left,...,15.2,54.0,96.2,78.7,41.0,3,3,296,0,7.8
1047,P01066,Hakim Ziyech,19,Moroccan,Morocco,26,Forward,188,81,Right,...,12.5,82.3,99.0,99.0,57.2,1,1,366,2,8.5
1495,P00170,Romelu Onana,20,Belgian,Belgium,14,Midfielder,184,75,Right,...,6.1,99.0,99.0,99.0,45.9,1,2,117,0,8.0
1800,P00152,Cody Lang,23,Dutch,Netherlands,22,Forward,190,83,Right,...,9.6,94.0,75.6,93.6,55.8,5,1,394,1,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52630,P00173,Youri Saelemaekers,19,Belgian,Belgium,17,Midfielder,176,76,Right,...,12.3,62.4,62.9,75.8,51.2,1,2,448,0,8.1
53228,P00644,Sergio Lapadula,22,Peruvian,Peru,20,Midfielder,182,76,Left,...,14.1,84.9,58.2,78.7,43.1,1,1,324,0,7.4
53882,P00727,Alistair Eustaquio,26,Canadian,Canada,25,Forward,184,80,Right,...,3.3,87.7,70.4,71.7,76.7,4,1,247,0,6.9
54112,P00907,Saleh Al-Qahtani,23,Saudi,Saudi Arabia,23,Forward,168,68,Right,...,15.9,99.0,76.2,87.5,99.0,1,1,280,1,7.3
54498,P00303,Nemanja Jevtovic,29,Serbian,Serbia,17,Midfielder,178,73,Right,...,13.1,88.9,82.3,80.9,77.8,1,2,224,0,7.7

In [19]:
#Query with variables

min_rating=8.0
nationality="Spanish"

df.query("player_rating>=@min_rating and nationality==@nationality")

#@ Symbol tells the query that this is a python variable from outside and not a column name

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
6658,P00074,Gavi Le Normand,25,Spanish,Spain,22,Forward,172,70,Right,...,9.9,83.7,70.2,99.0,77.9,1,1,244,0,8.6
8505,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,22.5,99.0,73.3,94.6,51.1,0,0,147,0,8.6
14282,P00072,Dani Gavi,21,Spanish,Spain,20,Midfielder,181,78,Right,...,11.6,76.2,91.1,95.0,47.2,0,0,115,0,8.3
14511,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,22.0,99.0,67.3,99.0,51.1,0,2,94,0,7.9
16491,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,2.1,48.2,33.8,42.5,60.4,0,1,115,0,7.6
21409,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,3.9,80.0,92.8,99.0,34.9,0,0,212,0,8.9
25742,P00076,Alvaro Gavi,28,Spanish,Spain,24,Forward,183,75,Right,...,6.7,62.0,99.0,84.9,48.4,2,2,501,0,8.2
34412,P00061,Ansu Alba,28,Spanish,Spain,9,Defender,193,83,Right,...,6.4,99.0,18.4,99.0,42.5,0,0,402,0,8.4
35861,P00074,Gavi Le Normand,25,Spanish,Spain,22,Forward,172,70,Right,...,7.1,88.3,97.9,99.0,52.2,0,0,341,0,8.0
49817,P00074,Gavi Le Normand,25,Spanish,Spain,22,Forward,172,70,Right,...,9.0,99.0,81.7,99.0,88.9,3,1,227,0,8.6

In [20]:
#Boolean masking V/S .query()

#using .query()
#Combined
df.query("goals>0 and assists>0 and player_rating>=7.0")

#using boolean masking
df[(df["goals"]>0) & (df["assists"]>0) & (df["player_rating"]>=7.0)]

#boolean masking with variable
rating=8.0
df[(df["goals"]>0) & (df["assists"]>0) & (df["player_rating"]>=rating)]

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
84,P00153,Memphis Zerrouki,25,Dutch,Netherlands,23,Forward,166,71,Right,...,15.5,91.4,98.5,99.0,75.0,2,1,165,0,8.4
1047,P01066,Hakim Ziyech,19,Moroccan,Morocco,26,Forward,188,81,Right,...,12.5,82.3,99.0,99.0,57.2,1,1,366,2,8.5
1495,P00170,Romelu Onana,20,Belgian,Belgium,14,Midfielder,184,75,Right,...,6.1,99.0,99.0,99.0,45.9,1,2,117,0,8.0
3211,P00438,Oleksandr Bondarenko,18,Ukrainian,Ukraine,22,Forward,182,76,Left,...,3.5,81.5,60.4,72.1,39.8,1,1,268,0,9.4
4167,P00907,Saleh Al-Qahtani,23,Saudi,Saudi Arabia,23,Forward,168,68,Right,...,11.8,99.0,99.0,99.0,70.1,3,2,520,2,9.0
5748,P01029,Idrissa Dia,22,Senegalese,Senegal,15,Midfielder,182,74,Right,...,6.6,67.6,65.2,71.6,55.7,2,1,182,0,8.3
6425,P00752,Celso Campbell,27,Costa Rican,Costa Rica,24,Forward,182,67,Right,...,10.5,75.3,50.9,99.0,33.0,2,4,319,0,8.7
7472,P00286,Rasmus Wind,19,Danish,Denmark,26,Forward,182,78,Right,...,6.5,61.8,79.1,74.7,44.3,1,2,210,0,8.8
12975,P00771,Damion Bishop,26,Jamaican,Jamaica,17,Midfielder,179,74,Right,...,10.0,66.9,64.5,66.6,37.3,2,5,502,0,7.7
17811,P01116,Andre Partey,27,Ghanaian,Ghana,24,Forward,174,69,Right,...,8.0,81.3,57.1,58.7,71.1,2,3,388,1,8.8
20705,P00373,Ludwig Elanga,29,Swedish,Sweden,9,Defender,172,70,Right,...,9.1,89.8,39.0,99.0,48.8,1,1,253,0,8.5
21434,P00490,Vinicius Nunes,23,Brazilian,Brazil,22,Forward,183,76,Right,...,17.4,99.0,93.0,99.0,46.0,2,6,362,0,8.5
21451,P00120,Sandro Bellanova,22,Italian,Italy,16,Midfielder,174,70,Right,...,10.5,81.0,99.0,83.4,70.0,1,2,178,0,7.7
22292,P01035,Sadio Diouf,24,Senegalese,Senegal,21,Forward,180,71,Right,...,7.5,88.9,55.2,96.9,63.0,5,2,463,0,8.4
22453,P01142,Vincent Choupo-Moting,25,Cameroonian,Cameroon,24,Forward,190,78,Right,...,5.1,99.0,70.7,94.4,56.9,2,2,207,0,8.8
23381,P00170,Romelu Onana,20,Belgian,Belgium,14,Midfielder,184,75,Right,...,27.6,99.0,99.0,99.0,60.5,1,1,171,0,8.0
28426,P00801,Anibal Sanchez,26,Panamanian,Panama,21,Forward,173,71,Right,...,19.9,81.7,75.6,99.0,80.9,1,2,319,0,8.1
29877,P01009,Mohannad Majeed,18,Iraqi,Iraq,21,Forward,187,75,Right,...,12.7,62.1,88.4,99.0,48.5,2,1,362,0,8.2
31311,P00699,Raul Torres,21,Mexican,Mexico,23,Forward,181,77,Left,...,15.1,99.0,99.0,99.0,66.2,4,2,296,0,8.6
32822,P01231,Mothobi Mokoena,33,South African,South Africa,9,Defender,188,76,Right,...,16.0,99.0,30.1,87.2,46.3,2,1,383,1,8.4
33672,P00311,Nemanja Savic,26,Serbian,Serbia,25,Forward,178,70,Right,...,8.0,46.6,65.9,63.1,73.3,7,2,464,1,8.3
34304,P00357,Mateusz Kozlowski,25,Polish,Poland,19,Midfielder,172,73,Right,...,28.7,99.0,99.0,99.0,43.9,1,2,336,0,8.0
35232,P01105,Mohammed Otoo,32,Ghanaian,Ghana,13,Midfielder,178,75,Right,...,20.0,78.5,99.0,99.0,74.5,1,1,200,0,9.3
36275,P00227,Andrej Bajkovic,24,Croatian,Croatia,19,Midfielder,181,79,Right,...,12.2,81.1,99.0,91.0,54.1,1,3,512,0,7.6
36768,P00907,Saleh Al-Qahtani,23,Saudi,Saudi Arabia,23,Forward,168,68,Right,...,8.8,98.7,82.6,99.0,68.4,4,1,200,0,8.4
38178,P00152,Cody Lang,23,Dutch,Netherlands,22,Forward,190,83,Right,...,19.1,85.6,87.1,97.9,57.6,3,1,397,0,8.2
38411,P00153,Memphis Zerrouki,25,Dutch,Netherlands,23,Forward,166,71,Right,...,10.5,99.0,99.0,99.0,50.9,6,3,293,2,8.5
38885,P00234,Dominik Kramaric,29,Croatian,Croatia,26,Forward,174,68,Right,...,8.9,99.0,99.0,99.0,61.2,2,1,276,1,8.4
39685,P01139,Samuel Olinga,28,Cameroonian,Cameroon,21,Forward,185,74,Left,...,12.0,83.7,88.6,60.9,68.5,2,1,440,0,8.9
43993,P00527,Yerry Barrios,22,Colombian,Colombia,7,Defender,193,77,Right,...,8.0,76.8,32.3,95.7,71.3,2,1,355,1,8.3
44702,P01009,Mohannad Majeed,18,Iraqi,Iraq,21,Forward,187,75,Right,...,14.9,97.1,99.0,99.0,22.5,3,1,318,1,7.9
45327,P01014,Safaa Mhawi,26,Iraqi,Iraq,26,Forward,184,75,Left,...,6.0,76.7,44.7,77.7,50.1,3,2,388,1,8.0
45431,P00490,Vinicius Nunes,23,Brazilian,Brazil,22,Forward,183,76,Right,...,11.3,99.0,90.4,99.0,49.8,2,2,265,0,8.5
45762,P00875,Hidajat Hazbavi,33,Iranian,Iran,17,Midfielder,184,79,Left,...,12.5,59.3,64.4,85.0,59.1,2,2,481,1,8.1
45944,P00125,Gianluigi Calafiori,25,Italian,Italy,21,Forward,189,77,Right,...,7.2,99.0,79.9,86.3,74.3,5,2,492,1,8.0
48654,P01009,Mohannad Majeed,18,Iraqi,Iraq,21,Forward,187,75,Right,...,12.3,99.0,95.2,99.0,65.2,2,1,344,1,7.9
49433,P01013,Amir Adnan,26,Iraqi,Iraq,25,Forward,176,76,Left,...,5.6,79.5,69.5,62.7,73.9,2,2,290,0,8.0
50190,P00901,Mohammed Al-Rubaie,25,Saudi,Saudi Arabia,17,Midfielder,180,72,Left,...,25.6,96.5,99.0,99.0,99.0,2,2,335,0,8.3
50263,P00457,John Armstrong,26,Scottish,Scotland,15,Midfielder,178,75,Right,...,22.9,99.0,99.0,99.0,99.0,2,3,225,1,8.6
50709,P01194,Yacine Bennacer,30,Algerian,Algeria,24,Forward,185,77,Left,...,4.1,62.4,76.7,65.6,53.1,1,1,217,0,8.9
52586,P01009,Mohannad Majeed,18,Iraqi,Iraq,21,Forward,187,75,Right,...,4.4,99.0,74.9,99.0,64.6,5,2,174,1,9.2

In [21]:
#if column name has spaces then use backticks in .query()
df.query("`jersey number`>3")

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
5,P00072,Dani Gavi,21,Spanish,Spain,20,Midfielder,181,78,Right,...,17.0,65.4,85.8,91.1,48.2,1,2,332,0,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54593,P01014,Safaa Mhawi,26,Iraqi,Iraq,26,Forward,184,75,Left,...,0.0,83.8,56.3,80.5,77.2,4,0,336,0,0.0
54594,P01007,Hussein Sadiq,25,Iraqi,Iraq,19,Midfielder,185,80,Left,...,0.0,39.0,51.1,50.6,29.9,0,1,338,0,0.0
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0

In [22]:
# .query with .loc
#display only player_name, goals, player_rating
df.query("goals>2").loc[:,["player_name","goals","player_rating"]]

# .query with .iloc
#nationality is brazilian and select rows from 0 to 4
df.query("nationality=='Brazilian'").iloc[:5]

,player_id,player_name,age,nationality,team,jersey number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
208,P00470,Vinicius Martins,34,Brazilian,Brazil,2,Goalkeeper,186,84,Left,...,0.7,29.1,14.3,44.9,64.0,0,0,258,0,6.2
209,P00488,Richarlison Junior,32,Brazilian,Brazil,20,Midfielder,182,76,Right,...,19.5,75.2,99.0,97.7,62.2,0,1,214,0,5.9
210,P00493,Casemiro Martins,30,Brazilian,Brazil,25,Forward,178,73,Left,...,5.5,69.7,68.0,81.8,51.9,4,0,295,0,5.6
211,P00481,Neymar Pereira,20,Brazilian,Brazil,13,Midfielder,183,75,Right,...,2.4,39.7,40.8,44.2,61.7,0,2,357,0,5.9
212,P00487,Alisson Reis,29,Brazilian,Brazil,19,Midfielder,175,71,Right,...,4.1,52.7,41.0,51.6,65.1,0,0,364,0,4.6