In [26]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Anand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Anand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Anand\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Anand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Anand\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### What is Pandas?

* Pandas is a python library built on top of NumPy that provides two powerful data structures - series and DataFrame - for working with structured data
* if NumPy is for raw numbers, Pandas is for tables. Every time you work with a csv file,excel file or database in python --> Use Pandas.

### Rules and Properties:
1. Pandas is built on top of NumPy - a DataFrame is a collection of NumPy arrays, One per column, organized into a table. NumPy gives you one array. Pandas gives you many arrays - one per column - presented together as a table.
2. Two main data structures- Series(1D) and DataFrame(2D).
3. Every row and column has a label- rows have an index,columns have names.
4. Each column has its own data type- one column can be int,another float,another string,another datetime. Each column has its own NumPy array with its own type.
5. Missing values are supported-represented as NaN.

In [27]:
#Series Vs DataFrame
#A series is a one-dimensional labelled array - like a single column from a table

import pandas as pd

ratings1=pd.Series([5.6,5.7,8.3,9.4,7.6],name="player_rating") #general indexing starting from 0
ratings2=pd.Series([5.6,5.7,8.3,9.4,7.6],name="player_rating",index=range(1,6)) #indexing from 1 to 5 using range
ratings3=pd.Series([5.6,5.7,8.3,9.4,7.6],name="player_rating",index=["P001","P002","P003","P004","P005"]) #idexing on our own
print(ratings1)
print(ratings2)
print(ratings3)

0    5.6
1    5.7
2    8.3
3    9.4
4    7.6
Name: player_rating, dtype: float64
1    5.6
2    5.7
3    8.3
4    9.4
5    7.6
Name: player_rating, dtype: float64
P001    5.6
P002    5.7
P003    8.3
P004    9.4
P005    7.6
Name: player_rating, dtype: float64

In [28]:
#From a dictionary-keys automatically become index
data={"P001":5.4,"P002":6.7,"P003":8.9}
ratings=pd.Series(data)
print(ratings)

P001    5.4
P002    6.7
P003    8.9
dtype: float64

In [29]:
#DataFrame
#A dataframe is a 2D labelled table-like an excel spreadsheet or a databse table
# #Each column is a series

#  small DataFrame 
data = {
    "player_name"  : ["Rodri Fati", "Ansu Le Normand", "Gavi Ramos"],
    "position"     : ["Goalkeeper", "Midfielder", "Midfielder"],
    "goals"        : [0, 0, 1],
    "player_rating": [5.6, 5.7, 8.3]
}
df=pd.DataFrame(data)
print(df)
print(type(df["goals"])) #class series bcz every column is a series
print(df.index) #range of index
print(df.columns) #column names
print(df.values) #NumPy array of all values
print(df.shape) #rows and columns in the table
print(df.dtypes) #data type of each column

       player_name    position  goals  player_rating
0       Rodri Fati  Goalkeeper      0            5.6
1  Ansu Le Normand  Midfielder      0            5.7
2       Gavi Ramos  Midfielder      1            8.3
<class 'pandas.Series'>
RangeIndex(start=0, stop=3, step=1)
Index(['player_name', 'position', 'goals', 'player_rating'], dtype='str')
[['Rodri Fati' 'Goalkeeper' 0 5.6]
 ['Ansu Le Normand' 'Midfielder' 0 5.7]
 ['Gavi Ramos' 'Midfielder' 1 8.3]]
(3, 4)
player_name          str
position             str
goals              int64
player_rating    float64
dtype: object

### Series Vs DataFrame
| | Series | DataFrame |
|---|---|---|
| Dimensions | 1D | 2D |
| Like | Single column | Full table |
| Has index | Yes | Yes — rows |
| Has column name | One name | Multiple column names |
| Think of as | One variable | Full dataset |

In [30]:
# To get current working directory
import os 
print(os.getcwd())
print(os.listdir()) #to list files in the cwd

c:\Users\Anand\Desktop\Python\Python Anand Notes
['.git', 'control flow.ipynb', 'Control_Flow_Practice.ipynb', 'Data', 'Datasets', 'DataStructures_Session.ipynb', 'Dictionaries.ipynb', 'Error handling.ipynb', 'f string formatting.ipynb', 'File handling.ipynb', 'Hospital_Practice_Lists.ipynb', 'Hospital_Practice_Sets_Dicts_Nested.ipynb', 'Hospital_Strings_Practice.ipynb', 'Lists & Tuples.ipynb', 'Logic Basics.ipynb', 'Loops & Iteration 1.ipynb', 'Loops & Iteration 2.ipynb', 'Loops_Iteration_1_Practice.ipynb', 'Modular Code 1.ipynb', 'Modular Code 2.ipynb', 'Numpy Core.ipynb', 'Orders.txt', 'Pandas Ingestion.ipynb', 'Pandas Selection.ipynb', 'prod', 'Products.txt', 'Python Quiz.ipynb', 'Python_Mixed_Practice_10Q.ipynb', 'PYT_05.ipynb', 'Sets.ipynb', 'Strings.ipynb', 'Theory_Revision_Reference.md']

In [31]:
#Loading files
#Syntax for loading a csv file
#pd.read_csv(filepath,parse_dates,index_col,use_cols,nrows)

import pandas as pd
df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv")
print(type(df))
print(df.shape)

<class 'pandas.DataFrame'>
(54600, 75)

| Argument | Description | Optional | Default |
|---|---|---|---|
| filepath | path to file | No | — |
| parse_dates | columns to parse as dates | Yes | False |
| index_col | column to use as row index | Yes | None |
| usecols | list of columns to load | Yes | all columns |
| nrows | number of rows to load | Yes | all rows |

In [32]:
#load with parse_dates
#Without parse_dates Pandas loads it as a plain string
#With parse_dates it loads as a proper datetimeobject you can filter and sort

#Without parse_dates
df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv")
print(df["match_date"].dtype)
print(df["match_date"][0])

#With parse_dates
df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"])
print(df["match_date"].dtype)
print(df["match_date"][0])

# Always use parse_dates for date columns only. 
# As a string you cannot filter by month or sort chronologically. 
# As datetime you can do all of that

str
10-07-2026
str
10-07-2026

In [33]:
print(df)

      player_id       player_name  ...  player_of_match_awards  \
0        P00055        Rodri Fati  ...                       0
1        P00070   Ansu Le Normand  ...                       0
2        P00066        Gavi Ramos  ...                       0
...         ...               ...  ...                     ...
54597    P01008     Ahmed Hussein  ...                       0
54598    P00991     Ibrahim Mhawi  ...                       0
54599    P00989  Mohannad Hussein  ...                       0

      tournament_rating
0                   5.8
1                   5.5
2                   8.4
...                 ...
54597               0.0
54598               0.0
54599               0.0

[54600 rows x 75 columns]

In [34]:
#with index_col
#with parse_dates
df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"],index_col="player_id")
print(df.index)
print(df) # Indexing starts with Player ID instead of 0,1,2,3....54599

Index(['P00055', 'P00070', 'P00066', 'P00073', 'P00059', 'P00072', 'P00058',
       'P00078', 'P00056', 'P00074',
       ...
       'P00994', 'P01003', 'P01005', 'P01014', 'P01007', 'P00996', 'P01006',
       'P01008', 'P00991', 'P00989'],
      dtype='str', name='player_id', length=54600)
                player_name  age  ... player_of_match_awards tournament_rating
player_id                         ...
P00055           Rodri Fati   26  ...                      0               5.8
P00070      Ansu Le Normand   19  ...                      0               5.5
P00066           Gavi Ramos   18  ...                      0               8.4
...                     ...  ...  ...                    ...               ...
P01008        Ahmed Hussein   26  ...                      0               0.0
P00991        Ibrahim Mhawi   30  ...                      0               0.0
P00989     Mohannad Hussein   27  ...                      0               0.0

[54600 rows x 74 columns]

In [35]:
#Load only n rows
df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"],index_col="player_id",nrows=1000)
print(df) # it will print only 1st 1000 rows

               player_name  age  ... player_of_match_awards tournament_rating
player_id                        ...
P00055          Rodri Fati   26  ...                      0               5.8
P00070     Ansu Le Normand   19  ...                      0               5.5
P00066          Gavi Ramos   18  ...                      0               8.4
...                    ...  ...  ...                    ...               ...
P00135       Cody Dumfries   30  ...                      0               5.7
P00140        Denzel Malen   27  ...                      0               6.4
P00148         Virgil Lang   22  ...                      0               4.8

[1000 rows x 74 columns]

In [36]:
#Load only specific columns
cols=["player_name","nationality","position"]
df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv",nrows=1000,usecols=cols)
print(df) # it will print only specifically mentioned column names with 1st 1000 rows

         player_name nationality    position
0         Rodri Fati     Spanish  Goalkeeper
1    Ansu Le Normand     Spanish  Midfielder
2         Gavi Ramos     Spanish  Midfielder
..               ...         ...         ...
997    Cody Dumfries       Dutch    Defender
998     Denzel Malen       Dutch    Defender
999      Virgil Lang       Dutch  Midfielder

[1000 rows x 3 columns]

In [37]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Anand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Anand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
#By default pd.read_excel always reads first sheet only
df1=pd.read_excel("./Datasets/fact&dimsample.xlsx")
print(df1)

     SalesID  ClientID  ...  UnitPrice  TotalPrice
0          1         1  ...     222630      222630
1          2         2  ...     222630      222630
2          3         3  ...     222630      222630
..       ...       ...  ...        ...         ...
948      949       948  ...     235000      235000
949      950       949  ...     235000      235000
950      951       950  ...     235000      235000

[951 rows x 8 columns]

In [39]:
#Read by sheet Name
df1=pd.read_excel("./Datasets/fact&dimsample.xlsx",sheet_name="dimSportsCars")
print(df1)

    SportsCarID  StyleID  ManufacturerID          Model  UnitPrice
0          1034       15              64           Roma     222630
1          1035       15              64     F8 Tributo     276000
2          1038       15              64  812 Superfast     350000
..          ...      ...             ...            ...        ...
16         1916       15             108      Senna GTR    1300000
17         1918       15             108      Speedtail    2200000
18         1919       15             108         Artura     235000

[19 rows x 5 columns]

In [40]:
#Read by sheet position (sheet number always starts from 0)
df1=pd.read_excel("./Datasets/fact&dimsample.xlsx",sheet_name=1)
print(df1)

     ClientID           ClientName
0           1       Hughes, Scot A
1           2        Rand, Adele G
2           3  Longo, Luisa Delmar
..        ...                  ...
997       998    Jessup, Crysta U.
998       999     Malone, Alfred Q
999      1000    Wimberly, Burl C.

[1000 rows x 2 columns]

In [41]:
#Multiple sheets by position at once
df1=pd.read_excel("./Datasets/fact&dimsample.xlsx",sheet_name=[1,2,3])
print(df1)

{1:      ClientID           ClientName
0           1       Hughes, Scot A
1           2        Rand, Adele G
2           3  Longo, Luisa Delmar
..        ...                  ...
997       998    Jessup, Crysta U.
998       999     Malone, Alfred Q
999      1000    Wimberly, Burl C.

[1000 rows x 2 columns], 2:     transaction_date  year  ...  year_quarter week_number
0         2020-01-01  2020  ...       2020-Q1           1
1         2020-01-02  2020  ...       2020-Q1           1
2         2020-01-03  2020  ...       2020-Q1           1
..               ...   ...  ...           ...         ...
728       2021-12-29  2021  ...       2021-Q4          53
729       2021-12-30  2021  ...       2021-Q4          53
730       2021-12-31  2021  ...       2021-Q4          53

[731 rows x 13 columns], 3:    ManufacturerID Manufacturer
0              64      Ferrari
1             108      McLaren}

In [42]:
#Multiple sheets by name at once
df1=pd.read_excel("./Datasets/fact&dimsample.xlsx",sheet_name=["dimClients","dimDate"])
print(df1)

{'dimClients':      ClientID           ClientName
0           1       Hughes, Scot A
1           2        Rand, Adele G
2           3  Longo, Luisa Delmar
..        ...                  ...
997       998    Jessup, Crysta U.
998       999     Malone, Alfred Q
999      1000    Wimberly, Burl C.

[1000 rows x 2 columns], 'dimDate':     transaction_date  year  ...  year_quarter week_number
0         2020-01-01  2020  ...       2020-Q1           1
1         2020-01-02  2020  ...       2020-Q1           1
2         2020-01-03  2020  ...       2020-Q1           1
..               ...   ...  ...           ...         ...
728       2021-12-29  2021  ...       2021-Q4          53
729       2021-12-30  2021  ...       2021-Q4          53
730       2021-12-31  2021  ...       2021-Q4          53

[731 rows x 13 columns]}

In [43]:
#all sheets at once
df1=pd.read_excel("./Datasets/fact&dimsample.xlsx",sheet_name=None)

for sheet_name,df in df1.items():
    print(f"{sheet_name}-{df.shape}")

 FactSportsCarSales -(951, 8)
dimClients-(1000, 2)
dimDate-(731, 13)
 dimManufacturers -(2, 2)
dimSportsCars-(19, 5)
dimStyles-(84, 2)

In [44]:
#Display options
#Pandas cut off display when there are too many rows and columns

#Set display options
#Show all columns-No truncation

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",6)
pd.set_option("display.max_colwidth",None)

df=pd.read_csv("./Datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"])
df.head(15)

#pd.reset_option("^display") #To reset display options

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,RB Salzburg,4384884,M00001,10-07-2026,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,72,0,0,0,0,0.00,0.00,0,15,26,0.59,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,4,0.83,0,1,0,0,7.8,0.7,26.5,13,23,81.9,5.6,50.9,3.3,48.2,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,Chelsea,4918927,M00001,10-07-2026,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,90,0,0,0,0,0.01,0.00,1,35,40,0.89,1,0,1,0,0,1,3,1,2,0,2,5,0,1,0,0,0,0,0.00,0,0,0,0,10.4,1.1,29.0,19,17,85.5,5.7,55.9,37.9,29.4,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,AIK,125015698,M00001,10-07-2026,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,73,1,0,2,0,0.08,0.07,2,72,85,0.85,0,0,3,0,1,1,0,0,1,2,4,2,0,0,0,0,0,0,0.00,0,0,0,0,8.8,1.3,33.7,30,19,88.8,8.3,82.9,79.8,78.6,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,P00076,Alvaro Gavi,28,Spanish,Spain,24,Forward,183,75,Right,PSV Eindhoven,13496935,M00001,10-07-2026,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,22,0,0,1,0,0.04,0.06,1,10,12,0.89,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,2.1,0.3,34.3,6,6,74.8,6.2,62.3,75.4,40.5,1.8,58.0,77.3,66.9,56.8,5,0,266,0,5.8
13,P00067,Rodri Alonso,25,Spanish,Spain,15,Midfielder,183,78,Right,RB Salzburg,9912074,M00001,10-07-2026,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,35,0,0,0,0,0.00,0.00,2,20,26,0.80,1,0,2,0,1,1,0,0,2,0,2,2,1,0,0,0,0,0,0.00,0,0,0,0,3.1,0.4,32.5,7,3,75.0,7.1,69.8,36.1,54.4,3.4,52.6,43.6,50.1,77.1,3,1,404,0,6.6
14,P00057,Gavi Asensio,22,Spanish,Spain,5,Defender,187,76,Right,Grasshoppers,1169641,M00001,10-07-2026,Hard Rock Stadium,Miami,South Africa,Group Stage,W,1,0,0,0,0,0,0,0.00,0.00,0,0,0,0.83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,83.7,0.0,0.0,24.3,45.4,0.0,48.5,27.0,54.1,38.9,0,0,213,0,0.0

In [45]:
#Inspection
#df.head()- First N rows

#shows first 5 rows by default

pd.set_option("display.max_columns",5)
df=pd.read_csv("./datasets/fifa_world_cup_2026_player_performance.csv",parse_dates=["match_date"])
print(df.head())
print(df.head(6))


#always run df.head() first after loading a file -it immediately tells you if the data is loaded

  player_id       player_name  ...  player_of_match_awards tournament_rating
0    P00055        Rodri Fati  ...                       0               5.8
1    P00070   Ansu Le Normand  ...                       0               5.5
2    P00066        Gavi Ramos  ...                       0               8.4
3    P00073     Pedro Cubarsi  ...                       0               6.7
4    P00059  Alvaro Oyarzabal  ...                       0               5.7

[5 rows x 75 columns]
  player_id       player_name  ...  player_of_match_awards tournament_rating
0    P00055        Rodri Fati  ...                       0               5.8
1    P00070   Ansu Le Normand  ...                       0               5.5
2    P00066        Gavi Ramos  ...                       0               8.4
3    P00073     Pedro Cubarsi  ...                       0               6.7
4    P00059  Alvaro Oyarzabal  ...                       0               5.7
5    P00072         Dani Gavi  ...                       0               6.7

[6 rows x 75 columns]

In [46]:
#Inspection
#df.head()- First N rows

#shows first 5 rows by default

cols=["player_name","nationality","age","player_id","goals","match_date"]
df=pd.read_csv("./datasets/fifa_world_cup_2026_player_performance.csv",usecols=cols,parse_dates=["match_date"])
print(df.head())
print(df.head(3))


#always run df.head() first after loading a file -it immediately tells you if the data is loaded

  player_id       player_name  ...  match_date goals
0    P00055        Rodri Fati  ...  10-07-2026     0
1    P00070   Ansu Le Normand  ...  10-07-2026     0
2    P00066        Gavi Ramos  ...  10-07-2026     1
3    P00073     Pedro Cubarsi  ...  10-07-2026     1
4    P00059  Alvaro Oyarzabal  ...  10-07-2026     0

[5 rows x 6 columns]
  player_id      player_name  ...  match_date goals
0    P00055       Rodri Fati  ...  10-07-2026     0
1    P00070  Ansu Le Normand  ...  10-07-2026     0
2    P00066       Gavi Ramos  ...  10-07-2026     1

[3 rows x 6 columns]

| Code | Meaning | Example |
|---|---|---|
| `%Y` | 4 digit year | 2026 |
| `%m` | 2 digit month | 07 |
| `%d` | 2 digit day | 10 |
| `%y` | 2 digit year | 26 |
| `%H` | Hour | 14 |
| `%M` | Minute | 30 |
| `%S` | Second | 45 |

In [47]:
#df.tail()-Last N rows
#shows last 5 rows by default

print(df.tail())
print(df.tail(10))

#can be used to verify if the last rows have been loaded correctly when working with large files.

      player_id       player_name  ...  match_date goals
54595    P00996       Amir Younis  ...  24-07-2026     0
54596    P01006  Safaa Al-Khafaji  ...  24-07-2026     0
54597    P01008     Ahmed Hussein  ...  24-07-2026     0
54598    P00991     Ibrahim Mhawi  ...  24-07-2026     0
54599    P00989  Mohannad Hussein  ...  24-07-2026     0

[5 rows x 6 columns]
      player_id       player_name  ...  match_date goals
54590    P00994     Ibrahim Daoud  ...  24-07-2026     0
54591    P01003     Ibrahim Taher  ...  24-07-2026     0
54592    P01005       Amir Majeed  ...  24-07-2026     0
...         ...               ...  ...         ...   ...
54597    P01008     Ahmed Hussein  ...  24-07-2026     0
54598    P00991     Ibrahim Mhawi  ...  24-07-2026     0
54599    P00989  Mohannad Hussein  ...  24-07-2026     0

[10 rows x 6 columns]

In [48]:
#df.info()

#One of the most important methods. shows:
# 1. Column names
# 2. Number of non null values-to detect missing data
# 3. Data type of each column
# 4. Memory usage


cols=["player_name","nationality","age","player_id","goals","match_date"]
df=pd.read_csv("./datasets/fifa_world_cup_2026_player_performance.csv",usecols=cols,parse_dates=["match_date"])
df["match_date"]=pd.to_datetime(df["match_date"],format="%d-%m-%Y")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_id    54600 non-null  str
 1   player_name  54600 non-null  str
 2   age          54600 non-null  int64
 3   nationality  54600 non-null  str
 4   match_date   54600 non-null  datetime64[us]
 5   goals        54600 non-null  int64
dtypes: datetime64[us](1), int64(2), str(3)
memory usage: 2.5 MB

In [49]:
#df.describe()

#shows statistics for all numeric columns automatically
df.describe() #numeric columns
df.describe(include="object") #stats for text columns

C:\Users\Anand\AppData\Local\Temp\ipykernel_25296\3937424492.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object") #stats for text columns

       player_id               player_name nationality
count      54600                     54600       54600
unique      1248                      1245          48
top       P00937  Pierre-Emile Christensen      Qatari
freq          66                        86        1716